public class AndroidRunner{
	public static void main(String args[]){
	Android.phone_detail="Asus";
	System.out.println("Android name is:"+Android.phone_detail);
	Android.price1=30000;
	System.out.println("Android price is:"+Android.price1);
	Android.color1="Black";
	System.out.println("Android color is:"+Android.color1);
	Android.weight1=15.4f;
	System.out.println("Android weight is:"+Android.weight1);
	Android.width1=2.2;
	System.out.println("Android width is:"+Android.width1);
	Android.is_good_product1=true;
	System.out.println("Android is good:"+Android.is_good_product1);
	Android.grade1='A';
	System.out.println("Android grade is:"+Android.grade1);
	Android.rating1=5;
	System.out.println("Android rating is:"+Android.rating1);
	Android.storage1=280;
	System.out.println("Android storage is:"+Android.storage1);
	Android.made_in1="India";
	System.out.println("Android made in is:"+Android.made_in1);
	Android.manufacture_year1=2023;
	System.out.println("Android manYear is:"+Android.manufacture_year1);
	Android.imei1=56598534794L;
	System.out.println("Android imei is:"+Android.imei1);
	Android.cemara1=50;
	System.out.println("Android Camera quality is:"+Android.cemara1);
	System.out.println("--------------static End--------------");

	
	Android phone=new Android();
	phone.name="Asus";
	System.out.println("Android name is:"+phone.name);
	phone.price=30000;
	System.out.println("Android price is:"+phone.price);
	phone.color="Black";
	System.out.println("Android Clour is:"+phone.color);
	phone.weight=15.4f;
	System.out.println("Android Weight is:"+phone.weight);
	phone.width=2.2;
	System.out.println("Android Width is:"+phone.width);
	phone.is_good_product=true;
	System.out.println("Android Usage is good :"+phone.is_good_product);
	phone.grade='A';
	System.out.println("Android Grade is:"+phone.grade);
	phone.rating=5;
	System.out.println("Android Rating is:"+phone.rating);
	phone.storage=280;
	System.out.println("Android storage is:"+phone.storage);
	phone.made_in="India";
	System.out.println("Android made in is:"+phone.made_in);
	phone.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+phone.manufacture_year);
	phone.imei=56598534794L;
	System.out.println("Android imei is:"+phone.imei);
	phone.cemara=50;
	System.out.println("Android cemara is:"+phone.cemara);
	System.out.println("--------------End--------------");
		Android detail=new Android();
	detail.name="Asus";
	System.out.println("Android name is:"+detail.name);
	detail.price=30000;
	System.out.println("Android price is:"+detail.price);
	detail.color="Black";
	System.out.println("Android Clour is:"+detail.color);
	detail.weight=15.4f;
	System.out.println("Android Weight is:"+detail.weight);
	detail.width=2.2;
	System.out.println("Android Width is:"+detail.width);
	detail.is_good_product=true;
	System.out.println("Android Usage is good :"+detail.is_good_product);
	detail.grade='A';
	System.out.println("Android Grade is:"+detail.grade);
	detail.rating=5;
	System.out.println("Android Rating is:"+detail.rating);
	detail.storage=280;
	System.out.println("Android storage is:"+detail.storage);
	detail.made_in="India";
	System.out.println("Android made in is:"+detail.made_in);
	detail.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+detail.manufacture_year);
	detail.imei=56598534794L;
	System.out.println("Android imei is:"+detail.imei);
	detail.cemara=50;
	System.out.println("Android cemara is:"+detail.cemara);
	System.out.println("--------------End--------------");
		Android gadget=new Android();
	gadget.name="Asus";
	System.out.println("Android name is:"+gadget.name);
	gadget.price=30000;
	System.out.println("Android price is:"+gadget.price);
	gadget.color="Black";
	System.out.println("Android Clour is:"+gadget.color);
	gadget.weight=15.4f;
	System.out.println("Android Weight is:"+gadget.weight);
	gadget.width=2.2;
	System.out.println("Android Width is:"+gadget.width);
	gadget.is_good_product=true;
	System.out.println("Android Usage is good :"+gadget.is_good_product);
	gadget.grade='A';
	System.out.println("Android Grade is:"+gadget.grade);
	gadget.rating=5;
	System.out.println("Android Rating is:"+gadget.rating);
	gadget.storage=280;
	System.out.println("Android storage is:"+gadget.storage);
	gadget.made_in="India";
	System.out.println("Android made in is:"+gadget.made_in);
	gadget.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+gadget.manufacture_year);
	gadget.imei=56598534794L;
	System.out.println("Android imei is:"+gadget.imei);
	gadget.cemara=50;
	System.out.println("Android cemara is:"+gadget.cemara);
	System.out.println("--------------End--------------");
		Android phone=new Android();
	phone.name="Asus";
	System.out.println("Android name is:"+phone.name);
	phone.price=30000;
	System.out.println("Android price is:"+phone.price);
	phone.color="Black";
	System.out.println("Android Clour is:"+phone.color);
	phone.weight=15.4f;
	System.out.println("Android Weight is:"+phone.weight);
	phone.width=2.2;
	System.out.println("Android Width is:"+phone.width);
	phone.is_good_product=true;
	System.out.println("Android Usage is good :"+phone.is_good_product);
	phone.grade='A';
	System.out.println("Android Grade is:"+phone.grade);
	phone.rating=5;
	System.out.println("Android Rating is:"+phone.rating);
	phone.storage=280;
	System.out.println("Android storage is:"+phone.storage);
	phone.made_in="India";
	System.out.println("Android made in is:"+phone.made_in);
	phone.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+phone.manufacture_year);
	phone.imei=56598534794L;
	System.out.println("Android imei is:"+phone.imei);
	phone.cemara=50;
	System.out.println("Android cemara is:"+phone.cemara);
	System.out.println("--------------End--------------");
		Android mobile=new Android();
	mobile.name="Asus";
	System.out.println("Android name is:"+mobile.name);
	mobile.price=30000;
	System.out.println("Android price is:"+mobile.price);
	mobile.color="Black";
	System.out.println("Android Clour is:"+mobile.color);
	mobile.weight=15.4f;
	System.out.println("Android Weight is:"+mobile.weight);
	mobile.width=2.2;
	System.out.println("Android Width is:"+mobile.width);
	mobile.is_good_product=true;
	System.out.println("Android Usage is good :"+mobile.is_good_product);
	mobile.grade='A';
	System.out.println("Android Grade is:"+mobile.grade);
	mobile.rating=5;
	System.out.println("Android Rating is:"+mobile.rating);
	mobile.storage=280;
	System.out.println("Android storage is:"+mobile.storage);
	mobile.made_in="India";
	System.out.println("Android made in is:"+mobile.made_in);
	mobile.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+mobile.manufacture_year);
	mobile.imei=56598534794L;
	System.out.println("Android imei is:"+mobile.imei);
	mobile.cemara=50;
	System.out.println("Android cemara is:"+mobile.cemara);
	System.out.println("--------------End--------------");
		Android phone_info=new Android();
	tab_info.name="Asus";
	System.out.println("Android name is:"+phone_info.name);
	tab_info.price=30000;
	System.out.println("Android price is:"+phone_info.price);
	tab_info.color="Black";
	System.out.println("Android Clour is:"+phone_info.color);
	tab_info.weight=15.4f;
	System.out.println("Android Weight is:"+phone_info.weight);
	tab_info.width=2.2;
	System.out.println("Android Width is:"+phone_info.width);
	tab_info.is_good_product=true;
	System.out.println("Android Usage is good :"+phone_info.is_good_product);
	tab_info.grade='A';
	System.out.println("Android Grade is:"+phone_info.grade);
	tab_info.rating=5;
	System.out.println("Android Rating is:"+phone_info.rating);
	tab_info.storage=280;
	System.out.println("Android storage is:"+phone_info.storage);
	tab_info.made_in="India";
	System.out.println("Android made in is:"+phone_info.made_in);
	tab_info.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+phone_info.manufacture_year);
	tab_info.imei=56598534794L;
	System.out.println("Android imei is:"+phone_info.imei);
	tab_info.cemara=50;
	System.out.println("Android cemara is:"+phone_info.cemara);
	System.out.println("--------------End--------------");
		Android amazon=new Android();
	amazon.name="Asus";
	System.out.println("Android name is:"+amazon.name);
	amazon.price=30000;
	System.out.println("Android price is:"+amazon.price);
	amazon.color="Black";
	System.out.println("Android Clour is:"+amazon.color);
	amazon.weight=15.4f;
	System.out.println("Android Weight is:"+amazon.weight);
	amazon.width=2.2;
	System.out.println("Android Width is:"+amazon.width);
	amazon.is_good_product=true;
	System.out.println("Android Usage is good :"+amazon.is_good_product);
	amazon.grade='A';
	System.out.println("Android Grade is:"+amazon.grade);
	amazon.rating=5;
	System.out.println("Android Rating is:"+amazon.rating);
	amazon.storage=280;
	System.out.println("Android storage is:"+amazon.storage);
	amazon.made_in="India";
	System.out.println("Android made in is:"+amazon.made_in);
	amazon.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+amazon.manufacture_year);
	amazon.imei=56598534794L;
	System.out.println("Android imei is:"+amazon.imei);
	amazon.cemara=50;
	System.out.println("Android cemara is:"+amazon.cemara);
	System.out.println("--------------End--------------");
		Android requirements=new Android();
	requirements.name="Asus";
	System.out.println("Android name is:"+requirements.name);
	requirements.price=30000;
	System.out.println("Android price is:"+requirements.price);
	requirements.color="Black";
	System.out.println("Android Clour is:"+requirements.color);
	requirements.weight=15.4f;
	System.out.println("Android Weight is:"+requirements.weight);
	requirements.width=2.2;
	System.out.println("Android Width is:"+requirements.width);
	requirements.is_good_product=true;
	System.out.println("Android Usage is good :"+requirements.is_good_product);
	requirements.grade='A';
	System.out.println("Android Grade is:"+requirements.grade);
	requirements.rating=5;
	System.out.println("Android Rating is:"+requirements.rating);
	requirements.storage=280;
	System.out.println("Android storage is:"+requirements.storage);
	requirements.made_in="India";
	System.out.println("Android made in is:"+requirements.made_in);
	requirements.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+requirements.manufacture_year);
	requirements.imei=56598534794L;
	System.out.println("Android imei is:"+requirements.imei);
	requirements.cemara=50;
	System.out.println("Android cemara is:"+requirements.cemara);
	System.out.println("--------------End--------------");
		Android features=new Android();
	features.name="Redmi";
	System.out.println("Android name is:"+features.name);
	features.price=30000;
	System.out.println("Android price is:"+features.price);
	features.color="Black";
	System.out.println("Android Clour is:"+features.color);
	features.weight=15.4f;
	System.out.println("Android Weight is:"+features.weight);
	features.width=2.2;
	System.out.println("Android Width is:"+features.width);
	features.is_good_product=true;
	System.out.println("Android Usage is good :"+features.is_good_product);
	features.grade='A';
	System.out.println("Android Grade is:"+features.grade);
	features.rating=5;
	System.out.println("Android Rating is:"+features.rating);
	features.storage=280;
	System.out.println("Android storage is:"+features.storage);
	features.made_in="India";
	System.out.println("Android made in is:"+features.made_in);
	features.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+features.manufacture_year);
	features.imei=56598534794L;
	System.out.println("Android imei is:"+features.imei);
	features.cemara=50;
	System.out.println("Android cemara is:"+features.cemara);
	System.out.println("--------------End--------------");
		Android mobile_info=new Android();
	mobile_info.name="Asus";
	System.out.println("Android name is:"+mobile_info.name);
	mobile_info.price=30000;
	System.out.println("Android price is:"+mobile_info.price);
	mobile_info.color="Black";
	System.out.println("Android Clour is:"+mobile_info.color);
	mobile_info.weight=15.4f;
	System.out.println("Android Weight is:"+mobile_info.weight);
	mobile_info.width=2.2;
	System.out.println("Android Width is:"+mobile_info.width);
	mobile_info.is_good_product=true;
	System.out.println("Android Usage is good :"+mobile_info.is_good_product);
	mobile_info.grade='A';
	System.out.println("Android Grade is:"+mobile_info.grade);
	mobile_info.rating=5;
	System.out.println("Android Rating is:"+mobile_info.rating);
	mobile_info.storage=280;
	System.out.println("Android storage is:"+mobile_info.storage);
	mobile_info.made_in="India";
	System.out.println("Android made in is:"+mobile_info.made_in);
	mobile_info.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+mobile_info.manufacture_year);
	mobile_info.imei=56598534794L;
	System.out.println("Android imei is:"+mobile_info.imei);
	mobile_info.cemara=50;
	System.out.println("Android cemara is:"+mobile_info.cemara);
	System.out.println("--------------End--------------");
		Android buyer_idea=new Android();
	buyer_idea.name="Realme";
	System.out.println("Android name is:"+buyer_idea.name);
	buyer_idea.price=30000;
	System.out.println("Android price is:"+buyer_idea.price);
	buyer_idea.color="Black";
	System.out.println("Android Clour is:"+buyer_idea.color);
	buyer_idea.weight=15.4f;
	System.out.println("Android Weight is:"+buyer_idea.weight);
	buyer_idea.width=2.2;
	System.out.println("Android Width is:"+buyer_idea.width);
	buyer_idea.is_good_product=true;
	System.out.println("Android Usage is good :"+buyer_idea.is_good_product);
	buyer_idea.grade='A';
	System.out.println("Android Grade is:"+buyer_idea.grade);
	buyer_idea.rating=5;
	System.out.println("Android Rating is:"+buyer_idea.rating);
	buyer_idea.storage=280;
	System.out.println("Android storage is:"+buyer_idea.storage);
	buyer_idea.made_in="India";
	System.out.println("Android made in is:"+buyer_idea.made_in);
	buyer_idea.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+buyer_idea.manufacture_year);
	buyer_idea.imei=56598534794L;
	System.out.println("Android imei is:"+buyer_idea.imei);
	buyer_idea.cemara=50;
	System.out.println("Android cemara is:"+buyer_idea.cemara);
	System.out.println("--------------End--------------");
		Android flipkart=new Android();
	flipkart.name="Samsung";
	System.out.println("Android name is:"+flipkart.name);
	flipkart.price=30000;
	System.out.println("Android price is:"+flipkart.price);
	flipkart.color="Black";
	System.out.println("Android Clour is:"+flipkart.color);
	flipkart.weight=15.4f;
	System.out.println("Android Weight is:"+flipkart.weight);
	flipkart.width=2.2;
	System.out.println("Android Width is:"+flipkart.width);
	flipkart.is_good_product=true;
	System.out.println("Android Usage is good :"+flipkart.is_good_product);
	flipkart.grade='A';
	System.out.println("Android Grade is:"+flipkart.grade);
	flipkart.rating=5;
	System.out.println("Android Rating is:"+flipkart.rating);
	flipkart.storage=280;
	System.out.println("Android storage is:"+flipkart.storage);
	flipkart.made_in="India";
	System.out.println("Android made in is:"+flipkart.made_in);
	flipkart.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+flipkart.manufacture_year);
	flipkart.imei=56598534794L;
	System.out.println("Android imei is:"+flipkart.imei);
	flipkart.cemara=50;
	System.out.println("Android cemara is:"+flipkart.cemara);
	System.out.println("--------------End--------------");
		Android gadget_info=new Android();
	gadget_info.name="Asus";
	System.out.println("Android name is:"+gadget_info.name);
	gadget_info.price=30000;
	System.out.println("Android price is:"+gadget_info.price);
	gadget_info.color="Black";
	System.out.println("Android Clour is:"+gadget_info.color);
	gadget_info.weight=15.4f;
	System.out.println("Android Weight is:"+gadget_info.weight);
	gadget_info.width=2.2;
	System.out.println("Android Width is:"+gadget_info.width);
	gadget_info.is_good_product=true;
	System.out.println("Android Usage is good :"+gadget_info.is_good_product);
	gadget_info.grade='A';
	System.out.println("Android Grade is:"+gadget_info.grade);
	gadget_info.rating=5;
	System.out.println("Android Rating is:"+gadget_info.rating);
	gadget_info.storage=280;
	System.out.println("Android storage is:"+gadget_info.storage);
	gadget_info.made_in="India";
	System.out.println("Android made in is:"+gadget_info.made_in);
	gadget_info.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+gadget_info.manufacture_year);
	gadget_info.imei=56598534794L;
	System.out.println("Android imei is:"+gadget_info.imei);
	gadget_info.cemara=50;
	System.out.println("Android cemara is:"+gadget_info.cemara);
	System.out.println("--------------End--------------");
		Android gadget_detail=new Android();
	gadget_detail.name="Asus";
	System.out.println("Android name is:"+gadget_detail.name);
	gadget_detail.price=30000;
	System.out.println("Android price is:"+gadget_detail.price);
	gadget_detail.color="Black";
	System.out.println("Android Clour is:"+gadget_detail.color);
	gadget_detail.weight=15.4f;
	System.out.println("Android Weight is:"+gadget_detail.weight);
	gadget_detail.width=2.2;
	System.out.println("Android Width is:"+gadget_detail.width);
	gadget_detail.is_good_product=true;
	System.out.println("Android Usage is good :"+gadget_detail.is_good_product);
	gadget_detail.grade='A';
	System.out.println("Android Grade is:"+gadget_detail.grade);
	gadget_detail.rating=5;
	System.out.println("Android Rating is:"+gadget_detail.rating);
	gadget_detail.storage=280;
	System.out.println("Android storage is:"+gadget_detail.storage);
	gadget_detail.made_in="India";
	System.out.println("Android made in is:"+gadget_detail.made_in);
	gadget_detail.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+gadget_detail.manufacture_year);
	gadget_detail.imei=56598534794L;
	System.out.println("Android imei is:"+gadget_detail.imei);
	gadget_detail.cemara=50;
	System.out.println("Android cemara is:"+gadget_detail.cemara);
	System.out.println("--------------End--------------");
		Android phone_details=new Android();
	phone_details.name="Asus";
	System.out.println("Android name is:"+phone_details.name);
	phone_details.price=30000;
	System.out.println("Android price is:"+phone_details.price);
	phone_details.color="Black";
	System.out.println("Android Clour is:"+phone_details.color);
	phone_details.weight=15.4f;
	System.out.println("Android Weight is:"+phone_details.weight);
	phone_details.width=2.2;
	System.out.println("Android Width is:"+phone_details.width);
	phone_details.is_good_product=true;
	System.out.println("Android Usage is good :"+phone_details.is_good_product);
	phone_details.grade='A';
	System.out.println("Android Grade is:"+phone_details.grade);
	phone_details.rating=5;
	System.out.println("Android Rating is:"+phone_details.rating);
	phone_details.storage=280;
	System.out.println("Android storage is:"+phone_details.storage);
	phone_details.made_in="India";
	System.out.println("Android made in is:"+phone_details.made_in);
	phone_details.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+phone_details.manufacture_year);
	phone_details.imei=56598534794L;
	System.out.println("Android imei is:"+phone_details.imei);
	phone_details.cemara=50;
	System.out.println("Android cemara is:"+phone_details.cemara);
	System.out.println("--------------End--------------");
		Android tab_collection=new Android();
	tab_collection.name="Asus";
	System.out.println("Android name is:"+tab_collection.name);
	tab_collection.price=30000;
	System.out.println("Android price is:"+tab_collection.price);
	tab_collection.color="Black";
	System.out.println("Android Clour is:"+tab_collection.color);
	tab_collection.weight=15.4f;
	System.out.println("Android Weight is:"+tab_collection.weight);
	tab_collection.width=2.2;
	System.out.println("Android Width is:"+tab_collection.width);
	tab_collection.is_good_product=true;
	System.out.println("Android Usage is good :"+tab_collection.is_good_product);
	tab_collection.grade='A';
	System.out.println("Android Grade is:"+tab_collection.grade);
	tab_collection.rating=5;
	System.out.println("Android Rating is:"+tab_collection.rating);
	tab_collection.storage=280;
	System.out.println("Android storage is:"+tab_collection.storage);
	tab_collection.made_in="India";
	System.out.println("Android made in is:"+tab_collection.made_in);
	tab_collection.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+tab_collection.manufacture_year);
	tab_collection.imei=56598534794L;
	System.out.println("Android imei is:"+tab_collection.imei);
	tab_collection.cemara=50;
	System.out.println("Android cemara is:"+tab_collection.cemara);
	System.out.println("--------------End--------------");
		Android apple_collection=new Android();
	apple_collection.name="Micromax";
	System.out.println("Android name is:"+apple_collection.name);
	apple_collection.price=30000;
	System.out.println("Android price is:"+apple_collection.price);
	apple_collection.color="Black";
	System.out.println("Android Clour is:"+apple_collection.color);
	apple_collection.weight=15.4f;
	System.out.println("Android Weight is:"+apple_collection.weight);
	apple_collection.width=2.2;
	System.out.println("Android Width is:"+apple_collection.width);
	apple_collection.is_good_product=true;
	System.out.println("Android Usage is good :"+apple_collection.is_good_product);
	apple_collection.grade='A';
	System.out.println("Android Grade is:"+apple_collection.grade);
	apple_collection.rating=5;
	System.out.println("Android Rating is:"+apple_collection.rating);
	apple_collection.storage=280;
	System.out.println("Android storage is:"+apple_collection.storage);
	apple_collection.made_in="India";
	System.out.println("Android made in is:"+apple_collection.made_in);
	apple_collection.manufacture_year=2023;
	System.out.println("Android manufacture year is:"+apple_collection.manufacture_year);
	apple_collection.imei=56598534794L;
	System.out.println("Android imei is:"+apple_collection.imei);
	apple_collection.cemara=50;
	System.out.println("Android cemara is:"+apple_collection.cemara);
	System.out.println("--------------End--------------");

	
	}




}





