public class ContainerRunner{
	public static void main(String args[]){
	Container.bottle_name1="Eagle";
	System.out.println("Container name is:"+Container.bottle_name1);
	Container.bottle_price1=200;
	System.out.println("Container price is:"+Container.bottle_price1);
	Container.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+Container.bottle_manufacture_per_Year1);
	Container.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+Container.bottle_manufacture_Year1);
	Container.bottle_rating1=5;
	System.out.println("Container rating is:"+Container.bottle_rating1);
	Container.bottle_is_good1=true;
	System.out.println("Container is good:"+Container.bottle_is_good1);
	Container.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+Container.bottle_grade_provided1);
	Container.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+Container.bottle_weight1);
	Container.bottle_height1=8.0;
	System.out.println("Container height is:"+Container.bottle_height1);
	Container.bottle_volume1=200;
	System.out.println("Container volume is:"+Container.bottle_volume1);
	Container.bottle1_name1="Milta";
	System.out.println("Container name is:"+Container.bottle1_name1);
	Container.bottle1_price1=220;
	System.out.println("Container price is:"+Container.bottle1_price1);
	Container.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+Container.bottle1_manufacture_per_Year1);
	System.out.println("--------------static End--------------");

	
	Container product=new Container();
	product.bottle_name1="Eagle";
	System.out.println("Container name is:"+product.bottle_name1);
	product.bottle_price1=200;
	System.out.println("Container price is:"+product.bottle_price1);
	product.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+product.bottle_manufacture_per_Year1);
	product.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+product.bottle_manufacture_Year1);
	product.bottle_rating1=5;
	System.out.println("Container rating is:"+product.bottle_rating1);
	product.bottle_is_good1=true;
	System.out.println("Container is good:"+product.bottle_is_good1);
	product.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+product.bottle_grade_provided1);
	product.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+product.bottle_weight1);
	product.bottle_height1=8.0;
	System.out.println("Container height is:"+product.bottle_height1);
	product.bottle_volume1=200;
	System.out.println("Container volume is:"+product.bottle_volume1);
	product.bottle1_name1="Milta";
	System.out.println("Container name is:"+product.bottle1_name1);
	product.bottle1_price1=220;
	System.out.println("Container price is:"+product.bottle1_price1);
	product.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+product.bottle1_manufacture_per_Year1);
	System.out.println("------------- End--------------");
	Container detail=new Container();
	detail.bottle_name1="Eagle";
	System.out.println("Container name is:"+detail.bottle_name1);
	detail.bottle_price1=200;
	System.out.println("Container price is:"+detail.bottle_price1);
	detail.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+detail.bottle_manufacture_per_Year1);
	detail.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+detail.bottle_manufacture_Year1);
	detail.bottle_rating1=5;
	System.out.println("Container rating is:"+detail.bottle_rating1);
	detail.bottle_is_good1=true;
	System.out.println("Container is good:"+detail.bottle_is_good1);
	detail.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+detail.bottle_grade_provided1);
	detail.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+detail.bottle_weight1);
	detail.bottle_height1=8.0;
	System.out.println("Container height is:"+detail.bottle_height1);
	detail.bottle_volume1=200;
	System.out.println("Container volume is:"+detail.bottle_volume1);
	detail.bottle1_name1="Milta";
	System.out.println("Container name is:"+detail.bottle1_name1);
	detail.bottle1_price1=220;
	System.out.println("Container price is:"+detail.bottle1_price1);
	detail.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+detail.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
	Container amazon=new Container();
	amazon.bottle_name1="Eagle";
	System.out.println("Container name is:"+amazon.bottle_name1);
	amazon.bottle_price1=200;
	System.out.println("Container price is:"+amazon.bottle_price1);
	amazon.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+amazon.bottle_manufacture_per_Year1);
	amazon.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+amazon.bottle_manufacture_Year1);
	amazon.bottle_rating1=5;
	System.out.println("Container rating is:"+amazon.bottle_rating1);
	amazon.bottle_is_good1=true;
	System.out.println("Container is good:"+amazon.bottle_is_good1);
	amazon.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+amazon.bottle_grade_provided1);
	amazon.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+amazon.bottle_weight1);
	amazon.bottle_height1=8.0;
	System.out.println("Container height is:"+amazon.bottle_height1);
	amazon.bottle_volume1=200;
	System.out.println("Container volume is:"+amazon.bottle_volume1);
	amazon.bottle1_name1="Milta";
	System.out.println("Container name is:"+amazon.bottle1_name1);
	amazon.bottle1_price1=220;
	System.out.println("Container price is:"+amazon.bottle1_price1);
	amazon.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+amazon.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
		Container flipkart=new Container();
	flipkart.bottle_name1="Eagle";
	System.out.println("Container name is:"+flipkart.bottle_name1);
	flipkart.bottle_price1=200;
	System.out.println("Container price is:"+flipkart.bottle_price1);
	flipkart.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+flipkart.bottle_manufacture_per_Year1);
	flipkart.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+flipkart.bottle_manufacture_Year1);
	flipkart.bottle_rating1=5;
	System.out.println("Container rating is:"+flipkart.bottle_rating1);
	flipkart.bottle_is_good1=true;
	System.out.println("Container is good:"+flipkart.bottle_is_good1);
	flipkart.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+flipkart.bottle_grade_provided1);
	flipkart.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+flipkart.bottle_weight1);
	flipkart.bottle_height1=8.0;
	System.out.println("Container height is:"+flipkart.bottle_height1);
	flipkart.bottle_volume1=200;
	System.out.println("Container volume is:"+flipkart.bottle_volume1);
	flipkart.bottle1_name1="Milta";
	System.out.println("Container name is:"+flipkart.bottle1_name1);
	flipkart.bottle1_price1=220;
	System.out.println("Container price is:"+flipkart.bottle1_price1);
	flipkart.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+flipkart.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
		Container info=new Container();
	info.bottle_name1="Eagle";
	System.out.println("Container name is:"+info.bottle_name1);
	info.bottle_price1=200;
	System.out.println("Container price is:"+info.bottle_price1);
	info.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+info.bottle_manufacture_per_Year1);
	info.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+info.bottle_manufacture_Year1);
	info.bottle_rating1=5;
	System.out.println("Container rating is:"+info.bottle_rating1);
	info.bottle_is_good1=true;
	System.out.println("Container is good:"+info.bottle_is_good1);
	info.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+info.bottle_grade_provided1);
	info.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+info.bottle_weight1);
	info.bottle_height1=8.0;
	System.out.println("Container height is:"+info.bottle_height1);
	info.bottle_volume1=200;
	System.out.println("Container volume is:"+info.bottle_volume1);
	info.bottle1_name1="Milta";
	System.out.println("Container name is:"+info.bottle1_name1);
	info.bottle1_price1=220;
	System.out.println("Container price is:"+info.bottle1_price1);
	info.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+info.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
		Container data=new Container();
	data.bottle_name1="Eagle";
	System.out.println("Container name is:"+data.bottle_name1);
	data.bottle_price1=200;
	System.out.println("Container price is:"+data.bottle_price1);
	data.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+data.bottle_manufacture_per_Year1);
	data.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+data.bottle_manufacture_Year1);
	data.bottle_rating1=5;
	System.out.println("Container rating is:"+data.bottle_rating1);
	data.bottle_is_good1=true;
	System.out.println("Container is good:"+data.bottle_is_good1);
	data.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+data.bottle_grade_provided1);
	data.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+data.bottle_weight1);
	data.bottle_height1=8.0;
	System.out.println("Container height is:"+data.bottle_height1);
	data.bottle_volume1=200;
	System.out.println("Container volume is:"+data.bottle_volume1);
	data.bottle1_name1="Milta";
	System.out.println("Container name is:"+data.bottle1_name1);
	data.bottle1_price1=220;
	System.out.println("Container price is:"+data.bottle1_price1);
	data.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+data.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
		Container requirements=new Container();
	requirements.bottle_name1="Eagle";
	System.out.println("Container name is:"+requirements.bottle_name1);
	requirements.bottle_price1=200;
	System.out.println("Container price is:"+requirements.bottle_price1);
	requirements.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+requirements.bottle_manufacture_per_Year1);
	requirements.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+requirements.bottle_manufacture_Year1);
	requirements.bottle_rating1=5;
	System.out.println("Container rating is:"+requirements.bottle_rating1);
	requirements.bottle_is_good1=true;
	System.out.println("Container is good:"+requirements.bottle_is_good1);
	requirements.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+requirements.bottle_grade_provided1);
	requirements.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+requirements.bottle_weight1);
	requirements.bottle_height1=8.0;
	System.out.println("Container height is:"+requirements.bottle_height1);
	requirements.bottle_volume1=200;
	System.out.println("Container volume is:"+requirements.bottle_volume1);
	requirements.bottle1_name1="Milta";
	System.out.println("Container name is:"+requirements.bottle1_name1);
	requirements.bottle1_price1=220;
	System.out.println("Container price is:"+requirements.bottle1_price1);
	requirements.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+requirements.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
		Container features=new Container();
	features.bottle_name1="Eagle";
	System.out.println("Container name is:"+features.bottle_name1);
	features.bottle_price1=200;
	System.out.println("Container price is:"+features.bottle_price1);
	features.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+features.bottle_manufacture_per_Year1);
	features.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+features.bottle_manufacture_Year1);
	features.bottle_rating1=5;
	System.out.println("Container rating is:"+features.bottle_rating1);
	features.bottle_is_good1=true;
	System.out.println("Container is good:"+features.bottle_is_good1);
	features.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+features.bottle_grade_provided1);
	features.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+features.bottle_weight1);
	features.bottle_height1=8.0;
	System.out.println("Container height is:"+features.bottle_height1);
	features.bottle_volume1=200;
	System.out.println("Container volume is:"+features.bottle_volume1);
	features.bottle1_name1="Milta";
	System.out.println("Container name is:"+features.bottle1_name1);
	features.bottle1_price1=220;
	System.out.println("Container price is:"+features.bottle1_price1);
	features.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+features.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
		Container bottle_info=new Container();
	bottle_info.bottle_name1="Eagle";
	System.out.println("Container name is:"+bottle_info.bottle_name1);
	bottle_info.bottle_price1=200;
	System.out.println("Container price is:"+bottle_info.bottle_price1);
	bottle_info.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+bottle_info.bottle_manufacture_per_Year1);
	bottle_info.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+bottle_info.bottle_manufacture_Year1);
	bottle_info.bottle_rating1=5;
	System.out.println("Container rating is:"+bottle_info.bottle_rating1);
	bottle_info.bottle_is_good1=true;
	System.out.println("Container is good:"+bottle_info.bottle_is_good1);
	bottle_info.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+bottle_info.bottle_grade_provided1);
	bottle_info.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+bottle_info.bottle_weight1);
	bottle_info.bottle_height1=8.0;
	System.out.println("Container height is:"+bottle_info.bottle_height1);
	bottle_info.bottle_volume1=200;
	System.out.println("Container volume is:"+bottle_info.bottle_volume1);
	bottle_info.bottle1_name1="Milta";
	System.out.println("Container name is:"+bottle_info.bottle1_name1);
	bottle_info.bottle1_price1=220;
	System.out.println("Container price is:"+bottle_info.bottle1_price1);
	bottle_info.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+bottle_info.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
		Container bottle_detail=new Container();
	bottle_detail.bottle_name1="Eagle";
	System.out.println("Container name is:"+bottle_detail.bottle_name1);
	bottle_detail.bottle_price1=200;
	System.out.println("Container price is:"+bottle_detail.bottle_price1);
	bottle_detail.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+bottle_detail.bottle_manufacture_per_Year1);
	bottle_detail.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+bottle_detail.bottle_manufacture_Year1);
	bottle_detail.bottle_rating1=5;
	System.out.println("Container rating is:"+bottle_detail.bottle_rating1);
	bottle_detail.bottle_is_good1=true;
	System.out.println("Container is good:"+bottle_detail.bottle_is_good1);
	bottle_detail.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+bottle_detail.bottle_grade_provided1);
	bottle_detail.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+bottle_detail.bottle_weight1);
	bottle_detail.bottle_height1=8.0;
	System.out.println("Container height is:"+bottle_detail.bottle_height1);
	bottle_detail.bottle_volume1=200;
	System.out.println("Container volume is:"+bottle_detail.bottle_volume1);
	bottle_detail.bottle1_name1="Milta";
	System.out.println("Container name is:"+bottle_detail.bottle1_name1);
	bottle_detail.bottle1_price1=220;
	System.out.println("Container price is:"+bottle_detail.bottle1_price1);
	bottle_detail.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+bottle_detail.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
		Container users=new Container();
	users.bottle_name1="Eagle";
	System.out.println("Container name is:"+users.bottle_name1);
	users.bottle_price1=200;
	System.out.println("Container price is:"+users.bottle_price1);
	users.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+users.bottle_manufacture_per_Year1);
	users.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+users.bottle_manufacture_Year1);
	users.bottle_rating1=5;
	System.out.println("Container rating is:"+users.bottle_rating1);
	users.bottle_is_good1=true;
	System.out.println("Container is good:"+users.bottle_is_good1);
	users.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+users.bottle_grade_provided1);
	users.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+users.bottle_weight1);
	users.bottle_height1=8.0;
	System.out.println("Container height is:"+users.bottle_height1);
	users.bottle_volume1=200;
	System.out.println("Container volume is:"+users.bottle_volume1);
	users.bottle1_name1="Milta";
	System.out.println("Container name is:"+users.bottle1_name1);
	users.bottle1_price1=220;
	System.out.println("Container price is:"+users.bottle1_price1);
	users.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+users.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
		Container bottle_information=new Container();
	bottle_information.bottle_name1="Eagle";
	System.out.println("Container name is:"+bottle_information.bottle_name1);
	bottle_information.bottle_price1=200;
	System.out.println("Container price is:"+bottle_information.bottle_price1);
	bottle_information.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+bottle_information.bottle_manufacture_per_Year1);
	bottle_information.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+bottle_information.bottle_manufacture_Year1);
	bottle_information.bottle_rating1=5;
	System.out.println("Container rating is:"+bottle_information.bottle_rating1);
	bottle_information.bottle_is_good1=true;
	System.out.println("Container is good:"+bottle_information.bottle_is_good1);
	bottle_information.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+bottle_information.bottle_grade_provided1);
	bottle_information.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+bottle_information.bottle_weight1);
	bottle_information.bottle_height1=8.0;
	System.out.println("Container height is:"+bottle_information.bottle_height1);
	bottle_information.bottle_volume1=200;
	System.out.println("Container volume is:"+bottle_information.bottle_volume1);
	bottle_information.bottle1_name1="Milta";
	System.out.println("Container name is:"+bottle_information.bottle1_name1);
	bottle_information.bottle1_price1=220;
	System.out.println("Container price is:"+bottle_information.bottle1_price1);
	bottle_information.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+bottle_information.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
		Container bottle=new Container();
	bottle.bottle_name1="Eagle";
	System.out.println("Container name is:"+bottle.bottle_name1);
	bottle.bottle_price1=200;
	System.out.println("Container price is:"+bottle.bottle_price1);
	bottle.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+bottle.bottle_manufacture_per_Year1);
	bottle.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+bottle.bottle_manufacture_Year1);
	bottle.bottle_rating1=5;
	System.out.println("Container rating is:"+bottle.bottle_rating1);
	bottle.bottle_is_good1=true;
	System.out.println("Container is good:"+bottle.bottle_is_good1);
	bottle.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+bottle.bottle_grade_provided1);
	bottle.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+bottle.bottle_weight1);
	bottle.bottle_height1=8.0;
	System.out.println("Container height is:"+bottle.bottle_height1);
	bottle.bottle_volume1=200;
	System.out.println("Container volume is:"+bottle.bottle_volume1);
	bottle.bottle1_name1="Milta";
	System.out.println("Container name is:"+bottle.bottle1_name1);
	bottle.bottle1_price1=220;
	System.out.println("Container price is:"+bottle.bottle1_price1);
	bottle.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+bottle.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
		
		Container bottle_collection=new Container();
	bottle_collection.bottle_name1="Eagle";
	System.out.println("Container name is:"+bottle_collection.bottle_name1);
	bottle_collection.bottle_price1=200;
	System.out.println("Container price is:"+bottle_collection.bottle_price1);
	bottle_collection.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+bottle_collection.bottle_manufacture_per_Year1);
	bottle_collection.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+bottle_collection.bottle_manufacture_Year1);
	bottle_collection.bottle_rating1=5;
	System.out.println("Container rating is:"+bottle_collection.bottle_rating1);
	bottle_collection.bottle_is_good1=true;
	System.out.println("Container is good:"+bottle_collection.bottle_is_good1);
	bottle_collection.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+bottle_collection.bottle_grade_provided1);
	bottle_collection.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+bottle_collection.bottle_weight1);
	bottle_collection.bottle_height1=8.0;
	System.out.println("Container height is:"+bottle_collection.bottle_height1);
	bottle_collection.bottle_volume1=200;
	System.out.println("Container volume is:"+bottle_collection.bottle_volume1);
	bottle_collection.bottle1_name1="Milta";
	System.out.println("Container name is:"+bottle_collection.bottle1_name1);
	bottle_collection.bottle1_price1=220;
	System.out.println("Container price is:"+bottle_collection.bottle1_price1);
	bottle_collection.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+bottle_collection.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
	Container application_collection=new Container();
	application_collection.bottle_name1="Eagle";
	System.out.println("Container name is:"+application_collection.bottle_name1);
	application_collection.bottle_price1=200;
	System.out.println("Container price is:"+application_collection.bottle_price1);
	application_collection.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+application_collection.bottle_manufacture_per_Year1);
	application_collection.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+application_collection.bottle_manufacture_Year1);
	application_collection.bottle_rating1=5;
	System.out.println("Container rating is:"+application_collection.bottle_rating1);
	application_collection.bottle_is_good1=true;
	System.out.println("Container is good:"+application_collection.bottle_is_good1);
	application_collection.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+application_collection.bottle_grade_provided1);
	application_collection.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+application_collection.bottle_weight1);
	application_collection.bottle_height1=8.0;
	System.out.println("Container height is:"+application_collection.bottle_height1);
	application_collection.bottle_volume1=200;
	System.out.println("Container volume is:"+application_collection.bottle_volume1);
	application_collection.bottle1_name1="Milta";
	System.out.println("Container name is:"+application_collection.bottle1_name1);
	application_collection.bottle1_price1=220;
	System.out.println("Container price is:"+application_collection.bottle1_price1);
	application_collection.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+application_collection.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");
	Container information=new Container();
	information.bottle_name1="Eagle";
	System.out.println("Container name is:"+information.bottle_name1);
	information.bottle_price1=200;
	System.out.println("Container price is:"+information.bottle_price1);
	information.bottle_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+information.bottle_manufacture_per_Year1);
	information.bottle_manufacture_Year1=2019;
	System.out.println("Container manufacture in is:"+information.bottle_manufacture_Year1);
	information.bottle_rating1=5;
	System.out.println("Container rating is:"+information.bottle_rating1);
	information.bottle_is_good1=true;
	System.out.println("Container is good:"+information.bottle_is_good1);
	information.bottle_grade_provided1='A';
	System.out.println("Container grade is:"+information.bottle_grade_provided1);
	information.bottle_weight1=1.7f;
	System.out.println("Container weight is:"+information.bottle_weight1);
	information.bottle_height1=8.0;
	System.out.println("Container height is:"+information.bottle_height1);
	information.bottle_volume1=200;
	System.out.println("Container volume is:"+information.bottle_volume1);
	information.bottle1_name1="Milta";
	System.out.println("Container name is:"+information.bottle1_name1);
	information.bottle1_price1=220;
	System.out.println("Container price is:"+information.bottle1_price1);
	information.bottle1_manufacture_per_Year1=100000L;
	System.out.println("Container man/year is:"+information.bottle1_manufacture_per_Year1);
	System.out.println("-------------- End--------------");

	
	}




}





