public class GameRunner{
	public static void main(String args[]){
	Game.name1="FreeFire";
	System.out.println("Game name is:"+Game.name1);
	Game.price1=0;
	System.out.println("Game price is:"+Game.price1);
	Game.size1="500Mb";
	System.out.println("Game Size is:"+Game.size1);
	Game.developed_by1="Garena";
	System.out.println("Game developed by is:"+Game.developed_by1);
	Game.internal_storge1=210.2;
	System.out.println("Game internal space is:"+Game.internal_storge1);
	Game.is_good_to_play1=true;
	System.out.println("Game is good:"+Game.is_good_to_play1);
	Game.grade1='A';
	System.out.println("Game grade is:"+Game.grade1);
	Game.rating1=5;
	System.out.println("Game rating is:"+Game.rating1);
	Game.non_active1=280;
	System.out.println("Game non active players is:"+Game.non_active1);
	Game.developed_in1=2015;
	System.out.println("Game developed in is:"+Game.developed_in1);
	Game.release_year1=2018;
	System.out.println("Game release year is:"+Game.release_year1);
	Game.players1=500000000000L;
	System.out.println("Game players is:"+Game.players1);
	Game.characters_in_game1=20;
	System.out.println("Game characters in game quality is:"+Game.characters_in_game1);
	System.out.println("--------------static End--------------");

	
	Game phone=new Game();
	phone.name="PubG";
	System.out.println("Game name is:"+phone.name);
	phone.price=0;
	System.out.println("Game price is:"+phone.price);
	phone.developed_by="Krafton";
	System.out.println("Game Clour is:"+phone.developed_by);
	phone.size=2.6f;
	System.out.println("Game size is:"+phone.size);
	phone.internal_storge=2.2;
	System.out.println("Game internal storge is:"+phone.internal_storge);
	phone.is_good_to_play=true;
	System.out.println("Game Usage is good :"+phone.is_good_to_play);
	phone.grade='A';
	System.out.println("Game Grade is:"+phone.grade);
	phone.rating=5;
	System.out.println("Game Rating is:"+phone.rating);
	phone.non_active=2800;
	System.out.println("Game non_active is:"+phone.non_active);
	phone.developed_in="India";
	System.out.println("Game made in is:"+phone.developed_in);
	phone.release_year=2018;
	System.out.println("Game manufacture year is:"+phone.release_year);
	phone.players=50000000000L;
	System.out.println("Game players is:"+phone.players);
	phone.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+phone.characters_in_game);
	System.out.println("--------------End--------------");
		Game detail=new Game();
	detail.name="PubG";
	System.out.println("Game name is:"+detail.name);
	detail.price=0;
	System.out.println("Game price is:"+detail.price);
	detail.developed_by="Krafton";
	System.out.println("Game Clour is:"+detail.developed_by);
	detail.size=2.6f;
	System.out.println("Game size is:"+detail.size);
	detail.internal_storge=2.2;
	System.out.println("Game internal storge is:"+detail.internal_storge);
	detail.is_good_to_play=true;
	System.out.println("Game Usage is good :"+detail.is_good_to_play);
	detail.grade='A';
	System.out.println("Game Grade is:"+detail.grade);
	detail.rating=5;
	System.out.println("Game Rating is:"+detail.rating);
	detail.non_active=2800;
	System.out.println("Game non_active is:"+detail.non_active);
	detail.developed_in="India";
	System.out.println("Game made in is:"+detail.developed_in);
	detail.release_year=2018;
	System.out.println("Game manufacture year is:"+detail.release_year);
	detail.players=50000000000L;
	System.out.println("Game players is:"+detail.players);
	detail.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+detail.characters_in_game);
	System.out.println("--------------End--------------");
		Game playstore=new Game();
	playstore.name="PubG";
	System.out.println("Game name is:"+playstore.name);
	playstore.price=0;
	System.out.println("Game price is:"+playstore.price);
	playstore.developed_by="Krafton";
	System.out.println("Game Clour is:"+playstore.developed_by);
	playstore.size=2.6f;
	System.out.println("Game size is:"+playstore.size);
	playstore.internal_storge=2.2;
	System.out.println("Game internal storge is:"+playstore.internal_storge);
	playstore.is_good_to_play=true;
	System.out.println("Game Usage is good :"+playstore.is_good_to_play);
	playstore.grade='A';
	System.out.println("Game Grade is:"+playstore.grade);
	playstore.rating=5;
	System.out.println("Game Rating is:"+playstore.rating);
	playstore.non_active=2800;
	System.out.println("Game non_active is:"+playstore.non_active);
	playstore.developed_in="India";
	System.out.println("Game made in is:"+playstore.developed_in);
	playstore.release_year=2018;
	System.out.println("Game manufacture year is:"+playstore.release_year);
	playstore.players=50000000000L;
	System.out.println("Game players is:"+playstore.players);
	playstore.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+playstore.characters_in_game);
	System.out.println("--------------End--------------");
		Game mobile=new Game();
	mobile.name="PubG";
	System.out.println("Game name is:"+mobile.name);
	mobile.price=0;
	System.out.println("Game price is:"+mobile.price);
	mobile.developed_by="Krafton";
	System.out.println("Game Clour is:"+mobile.developed_by);
	mobile.size=2.6f;
	System.out.println("Game size is:"+mobile.size);
	mobile.internal_storge=2.2;
	System.out.println("Game internal storge is:"+mobile.internal_storge);
	mobile.is_good_to_play=true;
	System.out.println("Game Usage is good :"+mobile.is_good_to_play);
	mobile.grade='A';
	System.out.println("Game Grade is:"+mobile.grade);
	mobile.rating=5;
	System.out.println("Game Rating is:"+mobile.rating);
	mobile.non_active=2800;
	System.out.println("Game non_active is:"+mobile.non_active);
	mobile.developed_in="India";
	System.out.println("Game made in is:"+mobile.developed_in);
	mobile.release_year=2018;
	System.out.println("Game manufacture year is:"+mobile.release_year);
	mobile.players=50000000000L;
	System.out.println("Game players is:"+mobile.players);
	mobile.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+mobile.characters_in_game);
	System.out.println("--------------End--------------");
		Game phone_info=new Game();
	phone_info.name="PubG";
	System.out.println("Game name is:"+phone_info.name);
	phone_info.price=0;
	System.out.println("Game price is:"+phone_info.price);
	phone_info.developed_by="Krafton";
	System.out.println("Game Clour is:"+phone_info.developed_by);
	phone_info.size=2.6f;
	System.out.println("Game size is:"+phone_info.size);
	phone_info.internal_storge=2.2;
	System.out.println("Game internal storge is:"+phone_info.internal_storge);
	phone_info.is_good_to_play=true;
	System.out.println("Game Usage is good :"+phone_info.is_good_to_play);
	phone_info.grade='A';
	System.out.println("Game Grade is:"+phone_info.grade);
	phone_info.rating=5;
	System.out.println("Game Rating is:"+phone_info.rating);
	phone_info.non_active=2800;
	System.out.println("Game non_active is:"+phone_info.non_active);
	phone_info.developed_in="India";
	System.out.println("Game made in is:"+phone_info.developed_in);
	phone_info.release_year=2018;
	System.out.println("Game manufacture year is:"+phone_info.release_year);
	phone_info.players=50000000000L;
	System.out.println("Game players is:"+phone_info.players);
	phone_info.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+phone_info.characters_in_game);
	System.out.println("--------------End--------------");
		Game krafton=new Game();
	krafton.name="PubG";
	System.out.println("Game name is:"+krafton.name);
	krafton.price=0;
	System.out.println("Game price is:"+krafton.price);
	krafton.developed_by="Krafton";
	System.out.println("Game Clour is:"+krafton.developed_by);
	krafton.size=2.6f;
	System.out.println("Game size is:"+krafton.size);
	krafton.internal_storge=2.2;
	System.out.println("Game internal storge is:"+krafton.internal_storge);
	krafton.is_good_to_play=true;
	System.out.println("Game Usage is good :"+krafton.is_good_to_play);
	krafton.grade='A';
	System.out.println("Game Grade is:"+krafton.grade);
	krafton.rating=5;
	System.out.println("Game Rating is:"+krafton.rating);
	krafton.non_active=2800;
	System.out.println("Game non_active is:"+krafton.non_active);
	krafton.developed_in="India";
	System.out.println("Game made in is:"+krafton.developed_in);
	krafton.release_year=2018;
	System.out.println("Game manufacture year is:"+krafton.release_year);
	krafton.players=50000000000L;
	System.out.println("Game players is:"+krafton.players);
	krafton.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+krafton.characters_in_game);
	System.out.println("--------------End--------------");
		Game requirements=new Game();
	requirements.name="PubG";
	System.out.println("Game name is:"+requirements.name);
	requirements.price=0;
	System.out.println("Game price is:"+requirements.price);
	requirements.developed_by="Krafton";
	System.out.println("Game Clour is:"+requirements.developed_by);
	requirements.size=2.6f;
	System.out.println("Game size is:"+requirements.size);
	requirements.internal_storge=2.2;
	System.out.println("Game internal storge is:"+requirements.internal_storge);
	requirements.is_good_to_play=true;
	System.out.println("Game Usage is good :"+requirements.is_good_to_play);
	requirements.grade='A';
	System.out.println("Game Grade is:"+requirements.grade);
	requirements.rating=5;
	System.out.println("Game Rating is:"+requirements.rating);
	requirements.non_active=2800;
	System.out.println("Game non_active is:"+requirements.non_active);
	requirements.developed_in="India";
	System.out.println("Game made in is:"+requirements.developed_in);
	requirements.release_year=2018;
	System.out.println("Game manufacture year is:"+requirements.release_year);
	requirements.players=50000000000L;
	System.out.println("Game players is:"+requirements.players);
	requirements.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+requirements.characters_in_game);
	System.out.println("--------------End--------------");
		Game features=new Game();
	features.name="PubG";
	System.out.println("Game name is:"+features.name);
	features.price=0;
	System.out.println("Game price is:"+features.price);
	features.developed_by="Krafton";
	System.out.println("Game Clour is:"+features.developed_by);
	features.size=2.6f;
	System.out.println("Game size is:"+features.size);
	features.internal_storge=2.2;
	System.out.println("Game internal storge is:"+features.internal_storge);
	features.is_good_to_play=true;
	System.out.println("Game Usage is good :"+features.is_good_to_play);
	features.grade='A';
	System.out.println("Game Grade is:"+features.grade);
	features.rating=5;
	System.out.println("Game Rating is:"+features.rating);
	features.non_active=2800;
	System.out.println("Game non_active is:"+features.non_active);
	features.developed_in="India";
	System.out.println("Game made in is:"+features.developed_in);
	features.release_year=2018;
	System.out.println("Game manufacture year is:"+features.release_year);
	features.players=50000000000L;
	System.out.println("Game players is:"+features.players);
	features.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+features.characters_in_game);
	System.out.println("--------------End--------------");
		Game game_info=new Game();
	game_info.name="PubG";
	System.out.println("Game name is:"+game_info.name);
	game_info.price=0;
	System.out.println("Game price is:"+game_info.price);
	game_info.developed_by="Krafton";
	System.out.println("Game Clour is:"+game_info.developed_by);
	game_info.size=2.6f;
	System.out.println("Game size is:"+game_info.size);
	game_info.internal_storge=2.2;
	System.out.println("Game internal storge is:"+game_info.internal_storge);
	game_info.is_good_to_play=true;
	System.out.println("Game Usage is good :"+game_info.is_good_to_play);
	game_info.grade='A';
	System.out.println("Game Grade is:"+game_info.grade);
	game_info.rating=5;
	System.out.println("Game Rating is:"+game_info.rating);
	game_info.non_active=2800;
	System.out.println("Game non_active is:"+game_info.non_active);
	game_info.developed_in="India";
	System.out.println("Game made in is:"+game_info.developed_in);
	game_info.release_year=2018;
	System.out.println("Game manufacture year is:"+game_info.release_year);
	game_info.players=50000000000L;
	System.out.println("Game players is:"+game_info.players);
	game_info.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+game_info.characters_in_game);
	System.out.println("--------------End--------------");
		Game game_detail=new Game();
	game_detail.name="PubG";
	System.out.println("Game name is:"+game_detail.name);
	game_detail.price=0;
	System.out.println("Game price is:"+game_detail.price);
	game_detail.developed_by="Krafton";
	System.out.println("Game Clour is:"+game_detail.developed_by);
	game_detail.size=2.6f;
	System.out.println("Game size is:"+game_detail.size);
	game_detail.internal_storge=2.2;
	System.out.println("Game internal storge is:"+game_detail.internal_storge);
	game_detail.is_good_to_play=true;
	System.out.println("Game Usage is good :"+game_detail.is_good_to_play);
	game_detail.grade='A';
	System.out.println("Game Grade is:"+game_detail.grade);
	game_detail.rating=5;
	System.out.println("Game Rating is:"+game_detail.rating);
	game_detail.non_active=2800;
	System.out.println("Game non_active is:"+game_detail.non_active);
	game_detail.developed_in="India";
	System.out.println("Game made in is:"+game_detail.developed_in);
	game_detail.release_year=2018;
	System.out.println("Game manufacture year is:"+game_detail.release_year);
	game_detail.players=50000000000L;
	System.out.println("Game players is:"+game_detail.players);
	game_detail.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+game_detail.characters_in_game);
	System.out.println("--------------End--------------");
		Game gamestore=new Game();
	gamestore.name="PubG";
	System.out.println("Game name is:"+gamestore.name);
	gamestore.price=0;
	System.out.println("Game price is:"+gamestore.price);
	gamestore.developed_by="Krafton";
	System.out.println("Game Clour is:"+gamestore.developed_by);
	gamestore.size=2.6f;
	System.out.println("Game size is:"+gamestore.size);
	gamestore.internal_storge=2.2;
	System.out.println("Game internal storge is:"+gamestore.internal_storge);
	gamestore.is_good_to_play=true;
	System.out.println("Game Usage is good :"+gamestore.is_good_to_play);
	gamestore.grade='A';
	System.out.println("Game Grade is:"+gamestore.grade);
	gamestore.rating=5;
	System.out.println("Game Rating is:"+gamestore.rating);
	gamestore.non_active=2800;
	System.out.println("Game non_active is:"+gamestore.non_active);
	gamestore.developed_in="India";
	System.out.println("Game made in is:"+gamestore.developed_in);
	gamestore.release_year=2018;
	System.out.println("Game manufacture year is:"+gamestore.release_year);
	gamestore.players=50000000000L;
	System.out.println("Game players is:"+gamestore.players);
	gamestore.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+gamestore.characters_in_game);
	System.out.println("--------------End--------------");
		Game game_information=new Game();
	game_information.name="PubG";
	System.out.println("Game name is:"+game_information.name);
	game_information.price=0;
	System.out.println("Game price is:"+game_information.price);
	game_information.developed_by="Krafton";
	System.out.println("Game Clour is:"+game_information.developed_by);
	game_information.size=2.6f;
	System.out.println("Game size is:"+game_information.size);
	game_information.internal_storge=2.2;
	System.out.println("Game internal storge is:"+game_information.internal_storge);
	game_information.is_good_to_play=true;
	System.out.println("Game Usage is good :"+game_information.is_good_to_play);
	game_information.grade='A';
	System.out.println("Game Grade is:"+game_information.grade);
	game_information.rating=5;
	System.out.println("Game Rating is:"+game_information.rating);
	game_information.non_active=2800;
	System.out.println("Game non_active is:"+game_information.non_active);
	game_information.developed_in="India";
	System.out.println("Game made in is:"+game_information.developed_in);
	game_information.release_year=2018;
	System.out.println("Game manufacture year is:"+game_information.release_year);
	game_information.players=50000000000L;
	System.out.println("Game players is:"+game_information.players);
	game_information.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+game_information.characters_in_game);
	System.out.println("--------------End--------------");
		Game gameplay=new Game();
	gameplay.name="PubG";
	System.out.println("Game name is:"+gameplay.name);
	gameplay.price=0;
	System.out.println("Game price is:"+gameplay.price);
	gameplay.developed_by="Krafton";
	System.out.println("Game Clour is:"+gameplay.developed_by);
	gameplay.size=2.6f;
	System.out.println("Game size is:"+gameplay.size);
	gameplay.internal_storge=2.2;
	System.out.println("Game internal storge is:"+gameplay.internal_storge);
	gameplay.is_good_to_play=true;
	System.out.println("Game Usage is good :"+gameplay.is_good_to_play);
	gameplay.grade='A';
	System.out.println("Game Grade is:"+gameplay.grade);
	gameplay.rating=5;
	System.out.println("Game Rating is:"+gameplay.rating);
	gameplay.non_active=2800;
	System.out.println("Game non_active is:"+gameplay.non_active);
	gameplay.developed_in="India";
	System.out.println("Game made in is:"+gameplay.developed_in);
	gameplay.release_year=2018;
	System.out.println("Game manufacture year is:"+gameplay.release_year);
	gameplay.players=50000000000L;
	System.out.println("Game players is:"+gameplay.players);
	gameplay.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+gameplay.characters_in_game);
	System.out.println("--------------End--------------");
		Game phone_details=new Game();
	phone_details.name="PubG";
	System.out.println("Game name is:"+phone_details.name);
	phone_details.price=0;
	System.out.println("Game price is:"+phone_details.price);
	phone_details.developed_by="Krafton";
	System.out.println("Game Clour is:"+phone_details.developed_by);
	phone_details.size=2.6f;
	System.out.println("Game size is:"+phone_details.size);
	phone_details.internal_storge=2.2;
	System.out.println("Game internal storge is:"+phone_details.internal_storge);
	phone_details.is_good_to_play=true;
	System.out.println("Game Usage is good :"+phone_details.is_good_to_play);
	phone_details.grade='A';
	System.out.println("Game Grade is:"+phone_details.grade);
	phone_details.rating=5;
	System.out.println("Game Rating is:"+phone_details.rating);
	phone_details.non_active=2800;
	System.out.println("Game non_active is:"+phone_details.non_active);
	phone_details.developed_in="India";
	System.out.println("Game made in is:"+phone_details.developed_in);
	phone_details.release_year=2018;
	System.out.println("Game manufacture year is:"+phone_details.release_year);
	phone_details.players=50000000000L;
	System.out.println("Game players is:"+phone_details.players);
	phone_details.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+phone_details.characters_in_game);
	System.out.println("--------------End--------------");
		Game game_collection=new Game();
	game_collection.name="PubG";
	System.out.println("Game name is:"+game_collection.name);
	game_collection.price=0;
	System.out.println("Game price is:"+game_collection.price);
	game_collection.developed_by="Krafton";
	System.out.println("Game Clour is:"+game_collection.developed_by);
	game_collection.size=2.6f;
	System.out.println("Game size is:"+game_collection.size);
	game_collection.internal_storge=2.2;
	System.out.println("Game internal storge is:"+game_collection.internal_storge);
	game_collection.is_good_to_play=true;
	System.out.println("Game Usage is good :"+game_collection.is_good_to_play);
	game_collection.grade='A';
	System.out.println("Game Grade is:"+game_collection.grade);
	game_collection.rating=5;
	System.out.println("Game Rating is:"+game_collection.rating);
	game_collection.non_active=2800;
	System.out.println("Game non_active is:"+game_collection.non_active);
	game_collection.developed_in="India";
	System.out.println("Game made in is:"+game_collection.developed_in);
	game_collection.release_year=2018;
	System.out.println("Game manufacture year is:"+game_collection.release_year);
	game_collection.players=50000000000L;
	System.out.println("Game players is:"+game_collection.players);
	game_collection.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+game_collection.characters_in_game);
	System.out.println("--------------End--------------");
		Game application_collection=new Game();
	application_collection.name="PubG";
	System.out.println("Game name is:"+application_collection.name);
	application_collection.price=0;
	System.out.println("Game price is:"+application_collection.price);
	application_collection.developed_by="Krafton";
	System.out.println("Game Clour is:"+application_collection.developed_by);
	application_collection.size=2.6f;
	System.out.println("Game size is:"+application_collection.size);
	application_collection.internal_storge=2.2;
	System.out.println("Game internal storge is:"+application_collection.internal_storge);
	application_collection.is_good_to_play=true;
	System.out.println("Game Usage is good :"+application_collection.is_good_to_play);
	application_collection.grade='A';
	System.out.println("Game Grade is:"+application_collection.grade);
	application_collection.rating=5;
	System.out.println("Game Rating is:"+application_collection.rating);
	application_collection.non_active=2800;
	System.out.println("Game non_active is:"+application_collection.non_active);
	application_collection.developed_in="India";
	System.out.println("Game made in is:"+application_collection.developed_in);
	application_collection.release_year=2018;
	System.out.println("Game manufacture year is:"+application_collection.release_year);
	application_collection.players=50000000000L;
	System.out.println("Game players is:"+application_collection.players);
	application_collection.characters_in_game=9;
	System.out.println("Game characters_in_game is:"+application_collection.characters_in_game);
	System.out.println("--------------End--------------");

	
	}




}





