public class GroceryItemRunner{
	public static void main(String args[]){
	GroceryItem.itemName2="Cornflor";
	System.out.println("Item name is:"+GroceryItem.itemName2);
	GroceryItem.itemPrice2=600;
	System.out.println("Item price is:"+GroceryItem.itemPrice2);
	GroceryItem.crop_size2=10000000L;
	System.out.println("Item Size is:"+GroceryItem.crop_size2);
	GroceryItem.total_in_market2=2000;
	System.out.println("Item Present in Market is:"+GroceryItem.total_in_market2);
	GroceryItem.itemRating2=5;
	System.out.println("Item rating is:"+GroceryItem.itemRating2);
	GroceryItem.isGood2=true;
	System.out.println("Item is good:"+GroceryItem.isGood2);
	GroceryItem.gradeProvided2='A';
	System.out.println("Item ranking is:"+GroceryItem.gradeProvided2);
	GroceryItem.itemWeight2=4.5f;
	System.out.println("Item weight is:"+GroceryItem.itemWeight2);
	GroceryItem.calories2=44.2;
	System.out.println("Item calories Obtain is:"+GroceryItem.calories2);
	GroceryItem.expiry_time2=1;
	System.out.println("Item Expiry is:"+GroceryItem.expiry_time2+"year");
	GroceryItem.item1Name1="Tamato Sauace";
	System.out.println("Item name is:"+GroceryItem.item1Name1);
	GroceryItem.item1Price1=250;
	System.out.println("Item price is:"+GroceryItem.item1Price1);
	GroceryItem.crop_size2=60000L;
	System.out.println("Item CropSize is:"+GroceryItem.crop_size2);
	System.out.println("--------------static End--------------");

	
	 GroceryItem product=new  GroceryItem();
	product.itemName="Cornflor";
	System.out.println("Item name is:"+product.itemName);
	product.itemPrice=600;
	System.out.println("Item price is:"+product.itemPrice);
	product.crop_size=10000000L;
	System.out.println("Item CropSize is:"+product.crop_size);
	product.total_in_market=2000;
	System.out.println("Item Size in Market is :"+product.total_in_market);
	product.itemRating=5;
	System.out.println("Item rating is:"+product.itemRating);
	product.isGood=true;
	System.out.println("Item  is good for health :"+product.isGood);
	product.gradeProvided='A';
	System.out.println("Item Grade is:"+product.gradeProvided);
	product.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+product.itemWeight);
	product.calories=44.2;
	System.out.println("Item calories Obtain is:"+product.calories);
	product.expiry_time=1";
	System.out.println("Item Expiry is:"+product.expiry_time+"Year");
	product.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+product.item1Name);
	product.item1Price=250;
	System.out.println("Item price is:"+product.item1Price);
	product.crop_size1=60000L;
	System.out.println("Item CropSize is:"+product.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem detail=new  GroceryItem();
	detail.itemName="Cornflor";
	System.out.println("Item name is:"+	detail.itemName);
	detail.itemPrice=600;
	System.out.println("Item price is:"+detail.itemPrice);
	detail.crop_size=10000000L;
	System.out.println("Item CropSize is:"+detail.crop_size);
	detail.total_in_market=2000;
	System.out.println("Item Size in Market is :"detail+detail.total_in_market);
	detail.itemRating=5;
	System.out.println("Item rating is:"+detail.itemRating);
	detail.isGood=true;
	System.out.println("Item  is good for health :"+detail.isGood);
	detail.gradeProvided='A';
	System.out.println("Item Grade is:"+detail.gradeProvided);
	detail.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+detail.itemWeight);
	detail.calories=44.2;
	System.out.println("Item calories Obtain is:"+detail.calories);
	detail.expiry_time=1";
	System.out.println("Item Expiry is:"+detail.expiry_time+"Year");
	detail.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+detail.item1Name);
	detail.item1Price=250;
	System.out.println("Item price is:"+detail.item1Price);
	detail.crop_size1=60000L;
	System.out.println("Item CropSize is:"+detail.crop_size1);
	System.out.println("--------------End--------------");
	 GroceryItem amazon=new  GroceryItem();
	amazon.itemName="Cornflor";
	System.out.println("Item name is:"+amazon.itemName);
	amazon.itemPrice=600;
	System.out.println("Item price is:"+amazon.itemPrice);
	amazon.crop_size=10000000L;
	System.out.println("Item CropSize is:"+amazon.crop_size);
	amazon.total_in_market=2000;
	System.out.println("Item Size in Market is :"+amazon.total_in_market);
	amazon.itemRating=5;
	System.out.println("Item rating is:"+amazon.itemRating);
	amazon.isGood=true;
	System.out.println("Item  is good for health :"+amazon.isGood);
	amazon.gradeProvided='A';
	System.out.println("Item Grade is:"+amazon.gradeProvided);
	amazon.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+amazon.itemWeight);
	amazon.calories=44.2;
	System.out.println("Item calories Obtain is:"+amazon.calories);
	amazon.expiry_time=1";
	System.out.println("Item Expiry is:"+amazon.expiry_time+"Year");
	amazon.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+amazon.item1Name);
	amazon.item1Price=250;
	System.out.println("Item price is:"+amazon.item1Price);
	amazon.crop_size1=60000L;
	System.out.println("Item CropSize is:"+amazon.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem flipkart=new  GroceryItem();
	flipkart.itemName="Cornflor";
	System.out.println("Item name is:"+flipkart.itemName);
	flipkart.itemPrice=600;
	System.out.println("Item price is:"+flipkart.itemPrice);
	flipkart.crop_size=10000000L;
	System.out.println("Item CropSize is:"+flipkart.crop_size);
	flipkart.total_in_market=2000;
	System.out.println("Item Size in Market is :"+flipkart.total_in_market);
	flipkart.itemRating=5;
	System.out.println("Item rating is:"+flipkart.itemRating);
	flipkart.isGood=true;
	System.out.println("Item  is good for health :"+flipkart.isGood);
	flipkart.gradeProvided='A';
	System.out.println("Item Grade is:"+flipkart.gradeProvided);
	flipkart.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+flipkart.itemWeight);
	flipkart.calories=44.2;
	System.out.println("Item calories Obtain is:"+flipkart.calories);
	flipkart.expiry_time=1";
	System.out.println("Item Expiry is:"+flipkart.expiry_time+"Year");
	flipkart.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+flipkart.item1Name);
	flipkart.item1Price=250;
	System.out.println("Item price is:"+flipkart.item1Price);
	flipkart.crop_size1=60000L;
	System.out.println("Item CropSize is:"+flipkart.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem info=new  GroceryItem();
	info.itemName="Cornflor";
	System.out.println("Item name is:"+info.itemName);
	info.itemPrice=600;
	System.out.println("Item price is:"+info.itemPrice);
	info.crop_size=10000000L;
	System.out.println("Item CropSize is:"+info.crop_size);
	info.total_in_market=2000;
	System.out.println("Item Size in Market is :"+info.total_in_market);
	info.itemRating=5;
	System.out.println("Item rating is:"+info.itemRating);
	info.isGood=true;
	System.out.println("Item  is good for health :"+info.isGood);
	info.gradeProvided='A';
	System.out.println("Item Grade is:"+info.gradeProvided);
	info.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+info.itemWeight);
	info.calories=44.2;
	System.out.println("Item calories Obtain is:"+info.calories);
	info.expiry_time=1";
	System.out.println("Item Expiry is:"+info.expiry_time+"Year");
	info.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+info.item1Name);
	info.item1Price=250;
	System.out.println("Item price is:"+info.item1Price);
	info.crop_size1=60000L;
	System.out.println("Item CropSize is:"+info.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem list=new  GroceryItem();
	list.itemName="Cornflor";
	System.out.println("Item name is:"+list.itemName);
	list.itemPrice=600;
	System.out.println("Item price is:"+list.itemPrice);
	list.crop_size=10000000L;
	System.out.println("Item CropSize is:"+list.crop_size);
	list.total_in_market=2000;
	System.out.println("Item Size in Market is :"+list.total_in_market);
	list.itemRating=5;
	System.out.println("Item rating is:"+list.itemRating);
	list.isGood=true;
	System.out.println("Item  is good for health :"+list.isGood);
	list.gradeProvided='A';
	System.out.println("Item Grade is:"+list.gradeProvided);
	list.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+list.itemWeight);
	list.calories=44.2;
	System.out.println("Item calories Obtain is:"+list.calories);
	list.expiry_time=1";
	System.out.println("Item Expiry is:"+list.expiry_time+"Year");
	list.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+list.item1Name);
	list.item1Price=250;
	System.out.println("Item price is:"+list.item1Price);
	list.crop_size1=60000L;
	System.out.println("Item CropSize is:"+list.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem requirements=new  GroceryItem();
	requirements.itemName="Cornflor";
	System.out.println("Item name is:"+requirements.itemName);
	requirements.itemPrice=600;
	System.out.println("Item price is:"+requirements.itemPrice);
	requirements.crop_size=10000000L;
	System.out.println("Item CropSize is:"+requirements.crop_size);
	requirements.total_in_market=2000;
	System.out.println("Item Size in Market is :"+requirements.total_in_market);
	requirements.itemRating=5;
	System.out.println("Item rating is:"+requirements.itemRating);
	requirements.isGood=true;
	System.out.println("Item  is good for health :"+requirements.isGood);
	requirements.gradeProvided='A';
	System.out.println("Item Grade is:"+requirements.gradeProvided);
	requirements.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+requirements.itemWeight);
	requirements.calories=44.2;
	System.out.println("Item calories Obtain is:"+requirements.calories);
	requirements.expiry_time=1";
	System.out.println("Item Expiry is:"+requirements.expiry_time+"Year");
	requirements.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+requirements.item1Name);
	requirements.item1Price=250;
	System.out.println("Item price is:"+requirements.item1Price);
	requirements.crop_size1=60000L;
	System.out.println("Item CropSize is:"+requirements.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem dmart=new  GroceryItem();
	dmart.itemName="Cornflor";
	System.out.println("Item name is:"+dmart.itemName);
	dmart.itemPrice=600;
	System.out.println("Item price is:"+dmart.itemPrice);
	dmart.crop_size=10000000L;
	System.out.println("Item CropSize is:"+dmart.crop_size);
	dmart.total_in_market=2000;
	System.out.println("Item Size in Market is :"+dmart.total_in_market);
	dmart.itemRating=5;
	System.out.println("Item rating is:"+dmart.itemRating);
	dmart.isGood=true;
	System.out.println("Item  is good for health :"+dmart.isGood);
	dmart.gradeProvided='A';
	System.out.println("Item Grade is:"+dmart.gradeProvided);
	dmart.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+dmart.itemWeight);
	dmart.calories=44.2;
	System.out.println("Item calories Obtain is:"+dmart.calories);
	dmart.expiry_time=1";
	System.out.println("Item Expiry is:"+dmart.expiry_time+"Year");
	dmart.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+dmart.item1Name);
	dmart.item1Price=250;
	System.out.println("Item price is:"+dmart.item1Price);
	dmart.crop_size1=60000L;
	System.out.println("Item CropSize is:"+dmart.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem item_info=new  GroceryItem();
	item_info.itemName="Cornflor";
	System.out.println("Item name is:"+item_info.itemName);
	item_info.itemPrice=600;
	System.out.println("Item price is:"+item_info.itemPrice);
	item_info.crop_size=10000000L;
	System.out.println("Item CropSize is:"+item_info.crop_size);
	item_info.total_in_market=2000;
	System.out.println("Item Size in Market is :"+item_info.total_in_market);
	item_info.itemRating=5;
	System.out.println("Item rating is:"+item_info.itemRating);
	item_info.isGood=true;
	System.out.println("Item  is good for health :"+item_info.isGood);
	item_info.gradeProvided='A';
	System.out.println("Item Grade is:"+item_info.gradeProvided);
	item_info.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+item_info.itemWeight);
	item_info.calories=44.2;
	System.out.println("Item calories Obtain is:"+item_info.calories);
	item_info.expiry_time=1";
	System.out.println("Item Expiry is:"+item_info.expiry_time+"Year");
	item_info.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+item_info.item1Name);
	item_info.item1Price=250;
	System.out.println("Item price is:"+item_info.item1Price);
	item_info.crop_size1=60000L;
	System.out.println("Item CropSize is:"+item_info.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem grocery_detail=new  GroceryItem();
	grocery_detail.itemName="Cornflor";
	System.out.println("Item name is:"+grocery_detail.itemName);
	grocery_detail.itemPrice=600;
	System.out.println("Item price is:"+grocery_detail.itemPrice);
	grocery_detail.crop_size=10000000L;
	System.out.println("Item CropSize is:"+grocery_detail.crop_size);
	grocery_detail.total_in_market=2000;
	System.out.println("Item Size in Market is :"+grocery_detail.total_in_market);
	grocery_detail.itemRating=5;
	System.out.println("Item rating is:"+grocery_detail.itemRating);
	grocery_detail.isGood=true;
	System.out.println("Item  is good for health :"+grocery_detail.isGood);
	grocery_detail.gradeProvided='A';
	System.out.println("Item Grade is:"+grocery_detail.gradeProvided);
	grocery_detail.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+grocery_detail.itemWeight);
	grocery_detail.calories=44.2;
	System.out.println("Item calories Obtain is:"+grocery_detail.calories);
	grocery_detail.expiry_time=1";
	System.out.println("Item Expiry is:"+grocery_detail.expiry_time+"Year");
	grocery_detail.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+grocery_detail.item1Name);
	grocery_detail.item1Price=250;
	System.out.println("Item price is:"+grocery_detail.item1Price);
	grocery_detail.crop_size1=60000L;
	System.out.println("Item CropSize is:"+grocery_detail.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem buyers=new  GroceryItem();
	buyers.itemName="Cornflor";
	System.out.println("Item name is:"+buyers.itemName);
	buyers.itemPrice=600;
	System.out.println("Item price is:"+buyers.itemPrice);
	buyers.crop_size=10000000L;
	System.out.println("Item CropSize is:"+buyers.crop_size);
	buyers.total_in_market=2000;
	System.out.println("Item Size in Market is :"+buyers.total_in_market);
	buyers.itemRating=5;
	System.out.println("Item rating is:"+buyers.itemRating);
	buyers.isGood=true;
	System.out.println("Item  is good for health :"+buyers.isGood);
	buyers.gradeProvided='A';
	System.out.println("Item Grade is:"+buyers.gradeProvided);
	buyers.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+buyers.itemWeight);
	buyers.calories=44.2;
	System.out.println("Item calories Obtain is:"+buyers.calories);
	buyers.expiry_time=1";
	System.out.println("Item Expiry is:"+buyers.expiry_time+"Year");
	buyers.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+buyers.item1Name);
	buyers.item1Price=250;
	System.out.println("Item price is:"+buyers.item1Price);
	buyers.crop_size1=60000L;
	System.out.println("Item CropSize is:"+buyers.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem data=new  GroceryItem();
	data.itemName="Cornflor";
	System.out.println("Item name is:"+data.itemName);
	data.itemPrice=600;
	System.out.println("Item price is:"+data.itemPrice);
	data.crop_size=10000000L;
	System.out.println("Item CropSize is:"+data.crop_size);
	data.total_in_market=2000;
	System.out.println("Item Size in Market is :"+data.total_in_market);
	data.itemRating=5;
	System.out.println("Item rating is:"+data.itemRating);
	data.isGood=true;
	System.out.println("Item  is good for health :"+data.isGood);
	data.gradeProvided='A';
	System.out.println("Item Grade is:"+data.gradeProvided);
	data.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+data.itemWeight);
	data.calories=44.2;
	System.out.println("Item calories Obtain is:"+data.calories);
	data.expiry_time=1";
	System.out.println("Item Expiry is:"+data.expiry_time+"Year");
	data.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+data.item1Name);
	data.item1Price=250;
	System.out.println("Item price is:"+data.item1Price);
	data.crop_size1=60000L;
	System.out.println("Item CropSize is:"+data.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem viewers=new  GroceryItem();
	viewers.itemName="Cornflor";
	System.out.println("Item name is:"+viewers.itemName);
	viewers.itemPrice=600;
	System.out.println("Item price is:"+viewers.itemPrice);
	viewers.crop_size=10000000L;
	System.out.println("Item CropSize is:"+viewers.crop_size);
	viewers.total_in_market=2000;
	System.out.println("Item Size in Market is :"+viewers.total_in_market);
	viewers.itemRating=5;
	System.out.println("Item rating is:"+viewers.itemRating);
	viewers.isGood=true;
	System.out.println("Item  is good for health :"+viewers.isGood);
	viewers.gradeProvided='A';
	System.out.println("Item Grade is:"+viewers.gradeProvided);
	viewers.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+viewers.itemWeight);
	viewers.calories=44.2;
	System.out.println("Item calories Obtain is:"+viewers.calories);
	viewers.expiry_time=1";
	System.out.println("Item Expiry is:"+viewers.expiry_time+"Year");
	viewers.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+viewers.item1Name);
	viewers.item1Price=250;
	System.out.println("Item price is:"+viewers.item1Price);
	viewers.crop_size1=60000L;
	System.out.println("Item CropSize is:"+viewers.crop_size1);
	System.out.println("--------------End--------------");
	 GroceryItem fooditems=new  GroceryItem();
	fooditems.itemName="Cornflor";
	System.out.println("Item name is:"+fooditems.itemName);
	fooditems.itemPrice=600;
	System.out.println("Item price is:"+fooditems.itemPrice);
	fooditems.crop_size=10000000L;
	System.out.println("Item CropSize is:"+fooditems.crop_size);
	fooditems.total_in_market=2000;
	System.out.println("Item Size in Market is :"+fooditems.total_in_market);
	fooditems.itemRating=5;
	System.out.println("Item rating is:"+fooditems.itemRating);
	fooditems.isGood=true;
	System.out.println("Item  is good for health :"+fooditems.isGood);
	fooditems.gradeProvided='A';
	System.out.println("Item Grade is:"+fooditems.gradeProvided);
	fooditems.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+fooditems.itemWeight);
	fooditems.calories=44.2;
	System.out.println("Item calories Obtain is:"+fooditems.calories);
	fooditems.expiry_time=1";
	System.out.println("Item Expiry is:"+fooditems.expiry_time+"Year");
	fooditems.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+fooditems.item1Name);
	fooditems.item1Price=250;
	System.out.println("Item price is:"+fooditems.item1Price);
	fooditems.crop_size1=60000L;
	System.out.println("Item CropSize is:"+fooditems.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem grocery_collection=new  GroceryItem();
	grocery_collection.itemName="Cornflor";
	System.out.println("Item name is:"+grocery_collection.itemName);
	grocery_collection.itemPrice=600;
	System.out.println("Item price is:"+grocery_collection.itemPrice);
	grocery_collection.crop_size=10000000L;
	System.out.println("Item CropSize is:"+grocery_collection.crop_size);
	grocery_collection.total_in_market=2000;
	System.out.println("Item Size in Market is :"+grocery_collection.total_in_market);
	grocery_collection.itemRating=5;
	System.out.println("Item rating is:"+grocery_collection.itemRating);
	grocery_collection.isGood=true;
	System.out.println("Item  is good for health :"+grocery_collection.isGood);
	grocery_collection.gradeProvided='A';
	System.out.println("Item Grade is:"+grocery_collection.gradeProvided);
	grocery_collection.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+grocery_collection.itemWeight);
	grocery_collection.calories=44.2;
	System.out.println("Item calories Obtain is:"+grocery_collection.calories);
	grocery_collection.expiry_time=1";
	System.out.println("Item Expiry is:"+grocery_collection.expiry_time+"Year");
	grocery_collection.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+grocery_collection.item1Name);
	grocery_collection.item1Price=250;
	System.out.println("Item price is:"+grocery_collection.item1Price);
	grocery_collection.crop_size1=60000L;
	System.out.println("Item CropSize is:"+grocery_collection.crop_size1);
	System.out.println("--------------End--------------");
		 GroceryItem collection=new  GroceryItem();
	collection.itemName="Cornflor";
	System.out.println("Item name is:"+collection.itemName);
	collection.itemPrice=600;
	System.out.println("Item price is:"+collection.itemPrice);
	collection.crop_size=10000000L;
	System.out.println("Item CropSize is:"+collection.crop_size);
	collection.total_in_market=2000;
	System.out.println("Item Size in Market is :"+collection.total_in_market);
	collection.itemRating=5;
	System.out.println("Item rating is:"+collection.itemRating);
	collection.isGood=true;
	System.out.println("Item  is good for health :"+collection.isGood);
	collection.gradeProvided='A';
	System.out.println("Item Grade is:"+collection.gradeProvided);
	collection.itemWeight=4.5f;
	System.out.println("Item weight Buyer Buy is:"+collection.itemWeight);
	collection.calories=44.2;
	System.out.println("Item calories Obtain is:"+collection.calories);
	collection.expiry_time=1";
	System.out.println("Item Expiry is:"+collection.expiry_time+"Year");
	collection.item1Name="Tamato Sauace";
	System.out.println("Item name is:"+collection.item1Name);
	collection.item1Price=250;
	System.out.println("Item price is:"+collection.item1Price);
	collection.crop_size1=60000L;
	System.out.println("Item CropSize is:"+collection.crop_size1);
	System.out.println("--------------End--------------");

	
	}




}





