public class IphoneRunner{
	public static void main(String args[]){
	Iphone.phone_detail="Apple";
	System.out.println("Iphone name is:"+Iphone.phone_detail);
	Iphone.price1=300000;
	System.out.println("Iphone price is:"+Iphone.price1);
	Iphone.color1="Black";
	System.out.println("Iphone color is:"+Iphone.color1);
	Iphone.weight1=15.4f;
	System.out.println("Iphone weight is:"+Iphone.weight1);
	Iphone.width1=2.2;
	System.out.println("Iphone width is:"+Iphone.width1);
	Iphone.is_good_product1=true;
	System.out.println("Iphone  is good:"+Iphone.is_good_product1);
	Iphone.grade1='A';
	System.out.println("Iphone grade is:"+Iphone.grade1);
	Iphone.rating1=5;
	System.out.println("Iphone rating is:"+Iphone.rating1);
	Iphone.storage1=280;
	System.out.println("Iphone storage is:"+Iphone.storage1);
	Iphone.made_in1="India";
	System.out.println("Iphone made in is:"+Iphone.made_in1);
	Iphone.manufacture_year1=2023;
	System.out.println("Iphone manYear is:"+Iphone.manufacture_year1);
	Iphone.imei1=56598534794L;
	System.out.println("Iphone imei is:"+Iphone.imei1);
	Iphone.cemara1=50;
	System.out.println("Iphone Camera quality is:"+Iphone.cemara1);
	System.out.println("--------------static End--------------");

	
	Iphone apple=new Iphone();
	apple.name="Apple";
	System.out.println("Iphone name is:"+apple.name);
	apple.price=30000;
	System.out.println("Iphone price is:"+apple.price);
	apple.color="Black";
	System.out.println("Iphone Clour is:"+apple.color);
	apple.weight=15.4f;
	System.out.println("Iphone Weight is:"+apple.weight);
	apple.width=2.2;
	System.out.println("Iphone Width is:"+apple.width);
	apple.is_good_product=true;
	System.out.println("Iphone Usage is good :"+apple.is_good_product);
	apple.grade='A';
	System.out.println("Iphone Grade is:"+apple.grade);
	apple.rating=5;
	System.out.println("Iphone Rating is:"+apple.rating);
	apple.storage=280;
	System.out.println("Iphone storage is:"+apple.storage);
	apple.made_in="India";
	System.out.println("Iphone made in is:"+apple.made_in);
	apple.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+apple.manufacture_year);
	apple.imei=56598534794L;
	System.out.println("Iphone imei is:"+apple.imei);
	apple.cemara=50;
	System.out.println("Iphone cemara is:"+apple.cemara);
	System.out.println("--------------End--------------");
		Iphone detail=new Iphone();
	detail.name="Apple";
	System.out.println("Iphone name is:"+detail.name);
	detail.price=30000;
	System.out.println("Iphone price is:"+detail.price);
	detail.color="Black";
	System.out.println("Iphone Clour is:"+detail.color);
	detail.weight=15.4f;
	System.out.println("Iphone Weight is:"+detail.weight);
	detail.width=2.2;
	System.out.println("Iphone Width is:"+detail.width);
	detail.is_good_product=true;
	System.out.println("Iphone Usage is good :"+detail.is_good_product);
	detail.grade='A';
	System.out.println("Iphone Grade is:"+detail.grade);
	detail.rating=5;
	System.out.println("Iphone Rating is:"+detail.rating);
	detail.storage=280;
	System.out.println("Iphone storage is:"+detail.storage);
	detail.made_in="India";
	System.out.println("Iphone made in is:"+detail.made_in);
	detail.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+detail.manufacture_year);
	detail.imei=56598534794L;
	System.out.println("Iphone imei is:"+detail.imei);
	detail.cemara=50;
	System.out.println("IphoneIphone cemara is:"+detail.cemara);
	System.out.println("--------------End--------------");
		Iphone gadget=new Iphone();
	gadget.name="Apple";
	System.out.println("Iphone name is:"+gadget.name);
	gadget.price=30000;
	System.out.println("Iphone price is:"+gadget.price);
	gadget.color="Black";
	System.out.println("Iphone Clour is:"+gadget.color);
	gadget.weight=15.4f;
	System.out.println("Iphone Weight is:"+gadget.weight);
	gadget.width=2.2;
	System.out.println("Iphone Width is:"+gadget.width);
	gadget.is_good_product=true;
	System.out.println("Iphone Usage is good :"+gadget.is_good_product);
	gadget.grade='A';
	System.out.println("Iphone Grade is:"+gadget.grade);
	gadget.rating=5;
	System.out.println("Iphone Rating is:"+gadget.rating);
	gadget.storage=280;
	System.out.println("Iphone storage is:"+gadget.storage);
	gadget.made_in="India";
	System.out.println("Iphone made in is:"+gadget.made_in);
	gadget.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+gadget.manufacture_year);
	gadget.imei=56598534794L;
	System.out.println("Iphone imei is:"+gadget.imei);
	gadget.cemara=50;
	System.out.println("Iphone cemara is:"+gadget.cemara);
	System.out.println("--------------End--------------");
		Iphone phone=new Iphone();
	phone.name="Apple";
	System.out.println("Iphone name is:"+phone.name);
	phone.price=30000;
	System.out.println("Iphone price is:"+phone.price);
	phone.color="Black";
	System.out.println("Iphone Clour is:"+phone.color);
	phone.weight=15.4f;
	System.out.println("Iphone Weight is:"+phone.weight);
	phone.width=2.2;
	System.out.println("Iphone Width is:"+phone.width);
	phone.is_good_product=true;
	System.out.println("Iphone Usage is good :"+phone.is_good_product);
	phone.grade='A';
	System.out.println("Iphone Grade is:"+phone.grade);
	phone.rating=5;
	System.out.println("Iphone Rating is:"+phone.rating);
	phone.storage=280;
	System.out.println("Iphone storage is:"+phone.storage);
	phone.made_in="India";
	System.out.println("Iphone made in is:"+phone.made_in);
	phone.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+phone.manufacture_year);
	phone.imei=56598534794L;
	System.out.println("Iphone imei is:"+phone.imei);
	phone.cemara=50;
	System.out.println("Iphone cemara is:"+phone.cemara);
	System.out.println("--------------End--------------");
		Iphone mobile=new Iphone();
	mobile.name="Apple";
	System.out.println("Iphone name is:"+mobile.name);
	mobile.price=30000;
	System.out.println("Iphone price is:"+mobile.price);
	mobile.color="Black";
	System.out.println("Iphone Clour is:"+mobile.color);
	mobile.weight=15.4f;
	System.out.println("Iphone Weight is:"+mobile.weight);
	mobile.width=2.2;
	System.out.println("Iphone Width is:"+mobile.width);
	mobile.is_good_product=true;
	System.out.println("Iphone Usage is good :"+mobile.is_good_product);
	mobile.grade='A';
	System.out.println("Iphone Grade is:"+mobile.grade);
	mobile.rating=5;
	System.out.println("Iphone Rating is:"+mobile.rating);
	mobile.storage=280;
	System.out.println("Iphone storage is:"+mobile.storage);
	mobile.made_in="India";
	System.out.println("Iphone made in is:"+mobile.made_in);
	mobile.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+mobile.manufacture_year);
	mobile.imei=56598534794L;
	System.out.println("Iphone imei is:"+mobile.imei);
	mobile.cemara=50;
	System.out.println("Iphone cemara is:"+mobile.cemara);
	System.out.println("--------------End--------------");
		Iphone tab_info=new Iphone();
	tab_info.name="Apple";
	System.out.println("Iphone name is:"+tab_info.name);
	tab_info.price=30000;
	System.out.println("Iphone price is:"+tab_info.price);
	tab_info.color="Black";
	System.out.println("Iphone Clour is:"+tab_info.color);
	tab_info.weight=15.4f;
	System.out.println("Iphone Weight is:"+tab_info.weight);
	tab_info.width=2.2;
	System.out.println("Iphone Width is:"+tab_info.width);
	tab_info.is_good_product=true;
	System.out.println("Iphone Usage is good :"+tab_info.is_good_product);
	tab_info.grade='A';
	System.out.println("Iphone Grade is:"+tab_info.grade);
	tab_info.rating=5;
	System.out.println("Iphone Rating is:"+tab_info.rating);
	tab_info.storage=280;
	System.out.println("Iphone storage is:"+tab_info.storage);
	tab_info.made_in="India";
	System.out.println("Iphone made in is:"+tab_info.made_in);
	tab_info.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+tab_info.manufacture_year);
	tab_info.imei=56598534794L;
	System.out.println("Iphone imei is:"+tab_info.imei);
	tab_info.cemara=50;
	System.out.println("Iphone cemara is:"+tab_info.cemara);
	System.out.println("--------------End--------------");
		Iphone amazon=new Iphone();
	amazon.name="Apple";
	System.out.println("Iphone name is:"+amazon.name);
	amazon.price=30000;
	System.out.println("Iphone price is:"+amazon.price);
	amazon.color="Black";
	System.out.println("Iphone Clour is:"+amazon.color);
	amazon.weight=15.4f;
	System.out.println("Iphone Weight is:"+amazon.weight);
	amazon.width=2.2;
	System.out.println("Iphone Width is:"+amazon.width);
	amazon.is_good_product=true;
	System.out.println("Iphone Usage is good :"+amazon.is_good_product);
	amazon.grade='A';
	System.out.println("Iphone Grade is:"+amazon.grade);
	amazon.rating=5;
	System.out.println("Iphone Rating is:"+amazon.rating);
	amazon.storage=280;
	System.out.println("Iphone storage is:"+amazon.storage);
	amazon.made_in="India";
	System.out.println("Iphone made in is:"+amazon.made_in);
	amazon.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+amazon.manufacture_year);
	amazon.imei=56598534794L;
	System.out.println("Iphone imei is:"+amazon.imei);
	amazon.cemara=50;
	System.out.println("Iphone cemara is:"+amazon.cemara);
	System.out.println("--------------End--------------");
		Iphone requirements=new Iphone();
	requirements.name="Apple";
	System.out.println("Iphone name is:"+requirements.name);
	requirements.price=30000;
	System.out.println("Iphone price is:"+requirements.price);
	requirements.color="Black";
	System.out.println("Iphone Clour is:"+requirements.color);
	requirements.weight=15.4f;
	System.out.println("Iphone Weight is:"+requirements.weight);
	requirements.width=2.2;
	System.out.println("Iphone Width is:"+requirements.width);
	requirements.is_good_product=true;
	System.out.println("Iphone Usage is good :"+requirements.is_good_product);
	requirements.grade='A';
	System.out.println("Iphone Grade is:"+requirements.grade);
	requirements.rating=5;
	System.out.println("Iphone Rating is:"+requirements.rating);
	requirements.storage=280;
	System.out.println("Iphone storage is:"+requirements.storage);
	requirements.made_in="India";
	System.out.println("Iphone made in is:"+requirements.made_in);
	requirements.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+requirements.manufacture_year);
	requirements.imei=56598534794L;
	System.out.println("Iphone imei is:"+requirements.imei);
	requirements.cemara=50;
	System.out.println("Iphone cemara is:"+requirements.cemara);
	System.out.println("--------------End--------------");
		Iphone features=new Iphone();
	features.name="Apple";
	System.out.println("Iphone name is:"+features.name);
	features.price=30000;
	System.out.println("Iphone price is:"+features.price);
	features.color="Black";
	System.out.println("Iphone Clour is:"+features.color);
	features.weight=15.4f;
	System.out.println("Iphone Weight is:"+features.weight);
	features.width=2.2;
	System.out.println("Iphone Width is:"+features.width);
	features.is_good_product=true;
	System.out.println("Iphone Usage is good :"+features.is_good_product);
	features.grade='A';
	System.out.println("Iphone Grade is:"+features.grade);
	features.rating=5;
	System.out.println("Iphone Rating is:"+features.rating);
	features.storage=280;
	System.out.println("Iphone storage is:"+features.storage);
	features.made_in="India";
	System.out.println("Iphone made in is:"+features.made_in);
	features.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+features.manufacture_year);
	features.imei=56598534794L;
	System.out.println("Iphone imei is:"+features.imei);
	features.cemara=50;
	System.out.println("Iphone cemara is:"+features.cemara);
	System.out.println("--------------End--------------");
		Iphone mobile_info=new Iphone();
	mobile_info.name="Apple";
	System.out.println("Iphone name is:"+mobile_info.name);
	mobile_info.price=30000;
	System.out.println("Iphone price is:"+mobile_info.price);
	mobile_info.color="Black";
	System.out.println("Iphone Clour is:"+mobile_info.color);
	mobile_info.weight=15.4f;
	System.out.println("Iphone Weight is:"+mobile_info.weight);
	mobile_info.width=2.2;
	System.out.println("Iphone Width is:"+mobile_info.width);
	mobile_info.is_good_product=true;
	System.out.println("Iphone Usage is good :"+mobile_info.is_good_product);
	mobile_info.grade='A';
	System.out.println("Iphone Grade is:"+mobile_info.grade);
	mobile_info.rating=5;
	System.out.println("Iphone Rating is:"+mobile_info.rating);
	mobile_info.storage=280;
	System.out.println("Iphone storage is:"+mobile_info.storage);
	mobile_info.made_in="India";
	System.out.println("Iphone made in is:"+mobile_info.made_in);
	mobile_info.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+mobile_info.manufacture_year);
	mobile_info.imei=56598534794L;
	System.out.println("Iphone imei is:"+mobile_info.imei);
	mobile_info.cemara=50;
	System.out.println("Iphone cemara is:"+mobile_info.cemara);
	System.out.println("--------------End--------------");
		Iphone buyer_idea=new Iphone();
	buyer_idea.name="Apple";
	System.out.println("Iphone name is:"+buyer_idea.name);
	buyer_idea.price=30000;
	System.out.println("Iphone price is:"+buyer_idea.price);
	buyer_idea.color="Black";
	System.out.println("Iphone Clour is:"+buyer_idea.color);
	buyer_idea.weight=15.4f;
	System.out.println("Iphone Weight is:"+buyer_idea.weight);
	buyer_idea.width=2.2;
	System.out.println("Iphone Width is:"+buyer_idea.width);
	buyer_idea.is_good_product=true;
	System.out.println("Iphone Usage is good :"+buyer_idea.is_good_product);
	buyer_idea.grade='A';
	System.out.println("Iphone Grade is:"+buyer_idea.grade);
	buyer_idea.rating=5;
	System.out.println("Iphone Rating is:"+buyer_idea.rating);
	buyer_idea.storage=280;
	System.out.println("Iphone storage is:"+buyer_idea.storage);
	buyer_idea.made_in="India";
	System.out.println("Iphone made in is:"+buyer_idea.made_in);
	buyer_idea.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+buyer_idea.manufacture_year);
	buyer_idea.imei=56598534794L;
	System.out.println("Iphone imei is:"+buyer_idea.imei);
	buyer_idea.cemara=50;
	System.out.println("Iphone cemara is:"+buyer_idea.cemara);
	System.out.println("--------------End--------------");
		Iphone flipkart=new Iphone();
	flipkart.name="Apple";
	System.out.println("Iphone name is:"+flipkart.name);
	flipkart.price=30000;
	System.out.println("Iphone price is:"+flipkart.price);
	flipkart.color="Black";
	System.out.println("Iphone Clour is:"+flipkart.color);
	flipkart.weight=15.4f;
	System.out.println("Iphone Weight is:"+flipkart.weight);
	flipkart.width=2.2;
	System.out.println("Iphone Width is:"+flipkart.width);
	flipkart.is_good_product=true;
	System.out.println("Iphone Usage is good :"+flipkart.is_good_product);
	flipkart.grade='A';
	System.out.println("Iphone Grade is:"+flipkart.grade);
	flipkart.rating=5;
	System.out.println("Iphone Rating is:"+flipkart.rating);
	flipkart.storage=280;
	System.out.println("Iphone storage is:"+flipkart.storage);
	flipkart.made_in="India";
	System.out.println("Iphone made in is:"+flipkart.made_in);
	flipkart.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+flipkart.manufacture_year);
	flipkart.imei=56598534794L;
	System.out.println("Iphone imei is:"+flipkart.imei);
	flipkart.cemara=50;
	System.out.println("Iphone cemara is:"+flipkart.cemara);
	System.out.println("--------------End--------------");
		Iphone gadget_info=new Iphone();
	gadget_info.name="Apple";
	System.out.println("Iphone name is:"+gadget_info.name);
	gadget_info.price=30000;
	System.out.println("Iphone price is:"+gadget_info.price);
	gadget_info.color="Black";
	System.out.println("Iphone Clour is:"+gadget_info.color);
	gadget_info.weight=15.4f;
	System.out.println("Iphone Weight is:"+gadget_info.weight);
	gadget_info.width=2.2;
	System.out.println("Iphone Width is:"+gadget_info.width);
	gadget_info.is_good_product=true;
	System.out.println("Iphone Usage is good :"+gadget_info.is_good_product);
	gadget_info.grade='A';
	System.out.println("Iphone Grade is:"+gadget_info.grade);
	gadget_info.rating=5;
	System.out.println("Iphone Rating is:"+gadget_info.rating);
	gadget_info.storage=280;
	System.out.println("Iphone storage is:"+gadget_info.storage);
	gadget_info.made_in="India";
	System.out.println("Iphone made in is:"+gadget_info.made_in);
	gadget_info.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+gadget_info.manufacture_year);
	gadget_info.imei=56598534794L;
	System.out.println("Iphone imei is:"+gadget_info.imei);
	gadget_info.cemara=50;
	System.out.println("Iphone cemara is:"+gadget_info.cemara);
	System.out.println("--------------End--------------");
		Iphone gadget_detail=new Iphone();
	gadget_detail.name="Apple";
	System.out.println("Iphone name is:"+gadget_detail.name);
	gadget_detail.price=30000;
	System.out.println("Iphone price is:"+gadget_detail.price);
	gadget_detail.color="Black";
	System.out.println("Iphone Clour is:"+gadget_detail.color);
	gadget_detail.weight=15.4f;
	System.out.println("Iphone Weight is:"+gadget_detail.weight);
	gadget_detail.width=2.2;
	System.out.println("Iphone Width is:"+gadget_detail.width);
	gadget_detail.is_good_product=true;
	System.out.println("Iphone Usage is good :"+gadget_detail.is_good_product);
	gadget_detail.grade='A';
	System.out.println("Iphone Grade is:"+gadget_detail.grade);
	gadget_detail.rating=5;
	System.out.println("Iphone Rating is:"+gadget_detail.rating);
	gadget_detail.storage=280;
	System.out.println("Iphone storage is:"+gadget_detail.storage);
	gadget_detail.made_in="India";
	System.out.println("Iphone made in is:"+gadget_detail.made_in);
	gadget_detail.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+gadget_detail.manufacture_year);
	gadget_detail.imei=56598534794L;
	System.out.println("Iphone imei is:"+gadget_detail.imei);
	gadget_detail.cemara=50;
	System.out.println("Iphone cemara is:"+gadget_detail.cemara);
	System.out.println("--------------End--------------");
		Iphone tab_details=new Iphone();
	tab_details.name="Apple";
	System.out.println("Iphone name is:"+tab_details.name);
	tab_details.price=30000;
	System.out.println("Iphone price is:"+tab_details.price);
	tab_details.color="Black";
	System.out.println("Iphone Clour is:"+tab_details.color);
	tab_details.weight=15.4f;
	System.out.println("Iphone Weight is:"+tab_details.weight);
	tab_details.width=2.2;
	System.out.println("Iphone Width is:"+tab_details.width);
	tab_details.is_good_product=true;
	System.out.println("Iphone Usage is good :"+tab_details.is_good_product);
	tab_details.grade='A';
	System.out.println("Iphone Grade is:"+tab_details.grade);
	tab_details.rating=5;
	System.out.println("Iphone Rating is:"+tab_details.rating);
	tab_details.storage=280;
	System.out.println("Iphone storage is:"+tab_details.storage);
	tab_details.made_in="India";
	System.out.println("Iphone made in is:"+tab_details.made_in);
	tab_details.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+tab_details.manufacture_year);
	tab_details.imei=56598534794L;
	System.out.println("Iphone imei is:"+tab_details.imei);
	tab_details.cemara=50;
	System.out.println("Iphone cemara is:"+tab_details.cemara);
	System.out.println("--------------End--------------");
		Iphone tab_collection=new Iphone();
	tab_collection.name="Apple";
	System.out.println("Iphone name is:"+tab_collection.name);
	tab_collection.price=30000;
	System.out.println("Iphone price is:"+tab_collection.price);
	tab_collection.color="Black";
	System.out.println("Iphone Clour is:"+tab_collection.color);
	tab_collection.weight=15.4f;
	System.out.println("Iphone Weight is:"+tab_collection.weight);
	tab_collection.width=2.2;
	System.out.println("Iphone Width is:"+tab_collection.width);
	tab_collection.is_good_product=true;
	System.out.println("Iphone Usage is good :"+tab_collection.is_good_product);
	tab_collection.grade='A';
	System.out.println("Iphone Grade is:"+tab_collection.grade);
	tab_collection.rating=5;
	System.out.println("Iphone Rating is:"+tab_collection.rating);
	tab_collection.storage=280;
	System.out.println("Iphone storage is:"+tab_collection.storage);
	tab_collection.made_in="India";
	System.out.println("Iphone made in is:"+tab_collection.made_in);
	tab_collection.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+tab_collection.manufacture_year);
	tab_collection.imei=56598534794L;
	System.out.println("Iphone imei is:"+tab_collection.imei);
	tab_collection.cemara=50;
	System.out.println("Iphone cemara is:"+tab_collection.cemara);
	System.out.println("--------------End--------------");
		Iphone apple_collection=new Iphone();
	apple_collection.name="Apple";
	System.out.println("Iphone name is:"+apple_collection.name);
	apple_collection.price=30000;
	System.out.println("Iphone price is:"+apple_collection.price);
	apple_collection.color="Black";
	System.out.println("Iphone Clour is:"+apple_collection.color);
	apple_collection.weight=15.4f;
	System.out.println("Iphone Weight is:"+apple_collection.weight);
	apple_collection.width=2.2;
	System.out.println("Iphone Width is:"+apple_collection.width);
	apple_collection.is_good_product=true;
	System.out.println("Iphone Usage is good :"+apple_collection.is_good_product);
	apple_collection.grade='A';
	System.out.println("Iphone Grade is:"+apple_collection.grade);
	apple_collection.rating=5;
	System.out.println("Iphone Rating is:"+apple_collection.rating);
	apple_collection.storage=280;
	System.out.println("Iphone storage is:"+apple_collection.storage);
	apple_collection.made_in="India";
	System.out.println("Iphone made in is:"+apple_collection.made_in);
	apple_collection.manufacture_year=2023;
	System.out.println("Iphone manufacture year is:"+apple_collection.manufacture_year);
	apple_collection.imei=56598534794L;
	System.out.println("Iphone imei is:"+apple_collection.imei);
	apple_collection.cemara=50;
	System.out.println("Iphone cemara is:"+apple_collection.cemara);
	System.out.println("--------------End--------------");

	
	}




}





