public class SparyRunner{
	public static void main(String args[]){
	Spary.spary_name1="Fog";
	System.out.println("Spary name is:"+Spary.spary_name1);
	Spary.spary_price1=200;
	System.out.println("Spary price is:"+Spary.spary_price1);
	Spary.spary_manufacture_per_Year1=100000L;
	System.out.println("Spary man/year is:"+Spary.spary_manufacture_per_Year1);
	Spary.spary_manufacture_Year1=2019;
	System.out.println("Spary manufacture in is:"+Spary.spary_manufacture_Year1);
	Spary.spary_rating1=5;
	System.out.println("Spary rating is:"+Spary.spary_rating1);
	Spary.spary_is_good1=true;
	System.out.println("Spary is good:"+Spary.spary_is_good1);
	Spary.spary_grade_provided1='A';
	System.out.println("Spary grade is:"+Spary.spary_grade_provided1);
	Spary.spary_weight1=1.7f;
	System.out.println("Spary weight is:"+Spary.spary_weight1);
	Spary.spary_height1=8.0;
	System.out.println("Spary height is:"+Spary.spary_height1);
	Spary.spary_volume1=200;
	System.out.println("Spary volume is:"+Spary.spary_volume1);
	Spary.spary1_name1="Poision";
	System.out.println("Spary name is:"+Spary.spary1_name1);
	Spary.spary1_price1=220;
	System.out.println("Spary price is:"+Spary.spary1_price1);
	Spary.spary1_manufacture_per_Year1=100000L;
	System.out.println("Spary man/year is:"+Spary.spary1_manufacture_per_Year1);
	System.out.println("--------------static End--------------");

	
	Spary product=new Spary();
	product.spary_name="Fog";
	System.out.println("Spary name is:"+product.spary_name);
	product.spary_price=200;
	System.out.println("Spary price is:"+product.spary_price);
	product.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+product.spary_manufacture_per_Year);
	product.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+product.spary_manufacture_Year);
	product.spary_rating=5;
	System.out.println("Spary rating is:"+product.spary_rating);
	product.spary_is_good=true;
	System.out.println("Spary Usage is good :"+product.spary_is_good);
	product.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+product.spary_grade_provided);
	product.spary_weight=1.7f;
	System.out.println("Spary weight is:"+product.spary_weight);
	product.spary_height=8.0;
	System.out.println("Spary height is:"+product.spary_height);
	product.spary_volume=200;
	System.out.println("Spary volume is:"+product.spary_volume);
	product.spary1_name="Posion";
	System.out.println("Spary name is:"+product.spary1_name);
	product.spary1_price=220;
	System.out.println("Spary price is:"+product.spary1_price);
	product.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+product.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary detail=new Spary();
		detail.spary_name="Fog";
	System.out.println("Spary name is:"+detail.spary_name);
	detail.spary_price=200;
	System.out.println("Spary price is:"+detail.spary_price);
	detail.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+detail.spary_manufacture_per_Year);
	detail.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+detail.spary_manufacture_Year);
	detail.spary_rating=5;
	System.out.println("Spary rating is:"+detail.spary_rating);
	detail.spary_is_good=true;
	System.out.println("Spary Usage is good :"+detail.spary_is_good);
	detail.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+detail.spary_grade_provided);
	detail.spary_weight=1.7f;
	System.out.println("Spary weight is:"+detail.spary_weight);
	detail.spary_height=8.0;
	System.out.println("Spary height is:"+detail.spary_height);
	detail.spary_volume=200;
	System.out.println("Spary volume is:"+detail.spary_volume);
	detail.spary1_name="Posion";
	System.out.println("Spary name is:"+detail.spary1_name);
	detail.spary1_price=220;
	System.out.println("Spary price is:"+detail.spary1_price);
	detail.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+detail.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
	Spary amazon=new Spary();
	amazon.spary_name="Fog";
	System.out.println("Spary name is:"+amazon.spary_name);
	amazon.spary_price=200;
	System.out.println("Spary price is:"+amazon.spary_price);
	amazon.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+amazon.spary_manufacture_per_Year);
	amazon.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+amazon.spary_manufacture_Year);
	amazon.spary_rating=5;
	System.out.println("Spary rating is:"+amazon.spary_rating);
	amazon.spary_is_good=true;
	System.out.println("Spary Usage is good :"+amazon.spary_is_good);
	amazon.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+amazon.spary_grade_provided);
	amazon.spary_weight=1.7f;
	System.out.println("Spary weight is:"+amazon.spary_weight);
	amazon.spary_height=8.0;
	System.out.println("Spary height is:"+amazon.spary_height);
	amazon.spary_volume=200;
	System.out.println("Spary volume is:"+amazon.spary_volume);
	amazon.spary1_name="Posion";
	System.out.println("Spary name is:"+amazon.spary1_name);
	amazon.spary1_price=220;
	System.out.println("Spary price is:"+amazon.spary1_price);
	amazon.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+amazon.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary flipkart=new Spary();
		flipkart.spary_name="Fog";
	System.out.println("Spary name is:"+flipkart.spary_name);
	flipkart.spary_price=200;
	System.out.println("Spary price is:"+flipkart.spary_price);
	flipkart.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+flipkart.spary_manufacture_per_Year);
	flipkart.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+flipkart.spary_manufacture_Year);
	flipkart.spary_rating=5;
	System.out.println("Spary rating is:"+flipkart.spary_rating);
	flipkart.spary_is_good=true;
	System.out.println("Spary Usage is good :"+flipkart.spary_is_good);
	flipkart.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+flipkart.spary_grade_provided);
	flipkart.spary_weight=1.7f;
	System.out.println("Spary weight is:"+flipkart.spary_weight);
	flipkart.spary_height=8.0;
	System.out.println("Spary height is:"+flipkart.spary_height);
	flipkart.spary_volume=200;
	System.out.println("Spary volume is:"+flipkart.spary_volume);
	flipkart.spary1_name="Posion";
	System.out.println("Spary name is:"+flipkart.spary1_name);
	flipkart.spary1_price=220;
	System.out.println("Spary price is:"+flipkart.spary1_price);
	flipkart.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+flipkart.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary info=new Spary();
		info.spary_name="Fog";
	System.out.println("Spary name is:"+info.spary_name);
	info.spary_price=200;
	System.out.println("Spary price is:"+info.spary_price);
	info.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+info.spary_manufacture_per_Year);
	info.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+info.spary_manufacture_Year);
	info.spary_rating=5;
	System.out.println("Spary rating is:"+info.spary_rating);
	info.spary_is_good=true;
	System.out.println("Spary Usage is good :"+info.spary_is_good);
	info.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+info.spary_grade_provided);
	info.spary_weight=1.7f;
	System.out.println("Spary weight is:"+info.spary_weight);
	info.spary_height=8.0;
	System.out.println("Spary height is:"+info.spary_height);
	info.spary_volume=200;
	System.out.println("Spary volume is:"+info.spary_volume);
	info.spary1_name="Posion";
	System.out.println("Spary name is:"+info.spary1_name);
	info.spary1_price=220;
	System.out.println("Spary price is:"+info.spary1_price);
	info.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+info.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary room=new Spary();
		room.spary_name="Fog";
	System.out.println("Spary name is:"+room.spary_name);
	room.spary_price=200;
	System.out.println("Spary price is:"+room.spary_price);
	room.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+room.spary_manufacture_per_Year);
	room.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+room.spary_manufacture_Year);
	room.spary_rating=5;
	System.out.println("Spary rating is:"+room.spary_rating);
	room.spary_is_good=true;
	System.out.println("Spary Usage is good :"+room.spary_is_good);
	room.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+room.spary_grade_provided);
	room.spary_weight=1.7f;
	System.out.println("Spary weight is:"+room.spary_weight);
	room.spary_height=8.0;
	System.out.println("Spary height is:"+room.spary_height);
	room.spary_volume=200;
	System.out.println("Spary volume is:"+room.spary_volume);
	room.spary1_name="Posion";
	System.out.println("Spary name is:"+room.spary1_name);
	room.spary1_price=220;
	System.out.println("Spary price is:"+room.spary1_price);
	room.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+room.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary requirements=new Spary();
		requirements.spary_name="Fog";
	System.out.println("Spary name is:"+requirements.spary_name);
	requirements.spary_price=200;
	System.out.println("Spary price is:"+requirements.spary_price);
	requirements.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+requirements.spary_manufacture_per_Year);
	requirements.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+requirements.spary_manufacture_Year);
	requirements.spary_rating=5;
	System.out.println("Spary rating is:"+requirements.spary_rating);
	requirements.spary_is_good=true;
	System.out.println("Spary Usage is good :"+requirements.spary_is_good);
	requirements.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+requirements.spary_grade_provided);
	requirements.spary_weight=1.7f;
	System.out.println("Spary weight is:"+requirements.spary_weight);
	requirements.spary_height=8.0;
	System.out.println("Spary height is:"+requirements.spary_height);
	requirements.spary_volume=200;
	System.out.println("Spary volume is:"+requirements.spary_volume);
	requirements.spary1_name="Posion";
	System.out.println("Spary name is:"+requirements.spary1_name);
	requirements.spary1_price=220;
	System.out.println("Spary price is:"+requirements.spary1_price);
	requirements.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+requirements.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary features=new Spary();
		features.spary_name="Fog";
	System.out.println("Spary name is:"+features.spary_name);
	features.spary_price=200;
	System.out.println("Spary price is:"+features.spary_price);
	features.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+features.spary_manufacture_per_Year);
	features.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+features.spary_manufacture_Year);
	features.spary_rating=5;
	System.out.println("Spary rating is:"+features.spary_rating);
	features.spary_is_good=true;
	System.out.println("Spary Usage is good :"+features.spary_is_good);
	features.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+features.spary_grade_provided);
	features.spary_weight=1.7f;
	System.out.println("Spary weight is:"+features.spary_weight);
	features.spary_height=8.0;
	System.out.println("Spary height is:"+features.spary_height);
	features.spary_volume=200;
	System.out.println("Spary volume is:"+features.spary_volume);
	features.spary1_name="Posion";
	System.out.println("Spary name is:"+features.spary1_name);
	features.spary1_price=220;
	System.out.println("Spary price is:"+features.spary1_price);
	features.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+features.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary spary_info=new Spary();
		spary_info.spary_name="Fog";
	System.out.println("Spary name is:"+spary_info.spary_name);
	spary_info.spary_price=200;
	System.out.println("Spary price is:"+spary_info.spary_price);
	spary_info.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+spary_info.spary_manufacture_per_Year);
	spary_info.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+spary_info.spary_manufacture_Year);
	spary_info.spary_rating=5;
	System.out.println("Spary rating is:"+spary_info.spary_rating);
	spary_info.spary_is_good=true;
	System.out.println("Spary Usage is good :"+spary_info.spary_is_good);
	spary_info.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+spary_info.spary_grade_provided);
	spary_info.spary_weight=1.7f;
	System.out.println("Spary weight is:"+spary_info.spary_weight);
	spary_info.spary_height=8.0;
	System.out.println("Spary height is:"+spary_info.spary_height);
	spary_info.spary_volume=200;
	System.out.println("Spary volume is:"+spary_info.spary_volume);
	spary_info.spary1_name="Posion";
	System.out.println("Spary name is:"+spary_info.spary1_name);
	spary_info.spary1_price=220;
	System.out.println("Spary price is:"+spary_info.spary1_price);
	spary_info.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+spary_info.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary spary_detail=new Spary();
		spary_detail.spary_name="Fog";
	System.out.println("Spary name is:"+spary_detail.spary_name);
	spary_detail.spary_price=200;
	System.out.println("Spary price is:"+spary_detail.spary_price);
	spary_detail.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+spary_detail.spary_manufacture_per_Year);
	spary_detail.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+spary_detail.spary_manufacture_Year);
	spary_detail.spary_rating=5;
	System.out.println("Spary rating is:"+spary_detail.spary_rating);
	spary_detail.spary_is_good=true;
	System.out.println("Spary Usage is good :"+spary_detail.spary_is_good);
	spary_detail.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+spary_detail.spary_grade_provided);
	spary_detail.spary_weight=1.7f;
	System.out.println("Spary weight is:"+spary_detail.spary_weight);
	spary_detail.spary_height=8.0;
	System.out.println("Spary height is:"+spary_detail.spary_height);
	spary_detail.spary_volume=200;
	System.out.println("Spary volume is:"+spary_detail.spary_volume);
	spary_detail.spary1_name="Posion";
	System.out.println("Spary name is:"+spary_detail.spary1_name);
	spary_detail.spary1_price=220;
	System.out.println("Spary price is:"+spary_detail.spary1_price);
	spary_detail.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+spary_detail.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary users=new Spary();
		users.spary_name="Fog";
	System.out.println("Spary name is:"+users.spary_name);
	users.spary_price=200;
	System.out.println("Spary price is:"+users.spary_price);
	users.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+users.spary_manufacture_per_Year);
	users.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+users.spary_manufacture_Year);
	users.spary_rating=5;
	System.out.println("Spary rating is:"+users.spary_rating);
	users.spary_is_good=true;
	System.out.println("Spary Usage is good :"+users.spary_is_good);
	users.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+users.spary_grade_provided);
	users.spary_weight=1.7f;
	System.out.println("Spary weight is:"+users.spary_weight);
	users.spary_height=8.0;
	System.out.println("Spary height is:"+users.spary_height);
	users.spary_volume=200;
	System.out.println("Spary volume is:"+users.spary_volume);
	users.spary1_name="Posion";
	System.out.println("Spary name is:"+users.spary1_name);
	users.spary1_price=220;
	System.out.println("Spary price is:"+users.spary1_price);
	users.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+users.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary spary_information=new Spary();
		spary_information.spary_name="Fog";
	System.out.println("Spary name is:"+spary_information.spary_name);
	spary_information.spary_price=200;
	System.out.println("Spary price is:"+spary_information.spary_price);
	spary_information.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+spary_information.spary_manufacture_per_Year);
	spary_information.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+spary_information.spary_manufacture_Year);
	spary_information.spary_rating=5;
	System.out.println("Spary rating is:"+spary_information.spary_rating);
	spary_information.spary_is_good=true;
	System.out.println("Spary Usage is good :"+spary_information.spary_is_good);
	spary_information.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+spary_information.spary_grade_provided);
	spary_information.spary_weight=1.7f;
	System.out.println("Spary weight is:"+spary_information.spary_weight);
	spary_information.spary_height=8.0;
	System.out.println("Spary height is:"+spary_information.spary_height);
	spary_information.spary_volume=200;
	System.out.println("Spary volume is:"+spary_information.spary_volume);
	spary_information.spary1_name="Posion";
	System.out.println("Spary name is:"+spary_information.spary1_name);
	spary_information.spary1_price=220;
	System.out.println("Spary price is:"+spary_information.spary1_price);
	spary_information.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+spary_information.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary spary=new Spary();
		spary.spary_name="Fog";
	System.out.println("Spary name is:"+spary.spary_name);
	spary.spary_price=200;
	System.out.println("Spary price is:"+spary.spary_price);
	spary.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+spary.spary_manufacture_per_Year);
	spary.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+spary.spary_manufacture_Year);
	spary.spary_rating=5;
	System.out.println("Spary rating is:"+spary.spary_rating);
	spary.spary_is_good=true;
	System.out.println("Spary Usage is good :"+spary.spary_is_good);
	spary.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+spary.spary_grade_provided);
	spary.spary_weight=1.7f;
	System.out.println("Spary weight is:"+spary.spary_weight);
	spary.spary_height=8.0;
	System.out.println("Spary height is:"+spary.spary_height);
	spary.spary_volume=200;
	System.out.println("Spary volume is:"+spary.spary_volume);
	spary.spary1_name="Posion";
	System.out.println("Spary name is:"+spary.spary1_name);
	spary.spary1_price=220;
	System.out.println("Spary price is:"+spary.spary1_price);
	spary.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+spary.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		
		Spary spary_collection=new Spary();
		spary_collection.spary_name="Fog";
	System.out.println("Spary name is:"+spary_collection.spary_name);
	spary_collection.spary_price=200;
	System.out.println("Spary price is:"+spary_collection.spary_price);
	spary_collection.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+spary_collection.spary_manufacture_per_Year);
	spary_collection.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+spary_collection.spary_manufacture_Year);
	spary_collection.spary_rating=5;
	System.out.println("Spary rating is:"+spary_collection.spary_rating);
	spary_collection.spary_is_good=true;
	System.out.println("Spary Usage is good :"+spary_collection.spary_is_good);
	spary_collection.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+spary_collection.spary_grade_provided);
	spary_collection.spary_weight=1.7f;
	System.out.println("Spary weight is:"+spary_collection.spary_weight);
	spary_collection.spary_height=8.0;
	System.out.println("Spary height is:"+spary_collection.spary_height);
	spary_collection.spary_volume=200;
	System.out.println("Spary volume is:"+spary_collection.spary_volume);
	spary_collection.spary1_name="Posion";
	System.out.println("Spary name is:"+spary_collection.spary1_name);
	spary_collection.spary1_price=220;
	System.out.println("Spary price is:"+spary_collection.spary1_price);
	spary_collection.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+spary_collection.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary application_collection=new Spary();
		application_collection.spary_name="Fog";
	System.out.println("Spary name is:"+application_collection.spary_name);
	application_collection.spary_price=200;
	System.out.println("Spary price is:"+application_collection.spary_price);
	application_collection.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+application_collection.spary_manufacture_per_Year);
	application_collection.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+application_collection.spary_manufacture_Year);
	application_collection.spary_rating=5;
	System.out.println("Spary rating is:"+application_collection.spary_rating);
	application_collection.spary_is_good=true;
	System.out.println("Spary Usage is good :"+application_collection.spary_is_good);
	application_collection.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+application_collection.spary_grade_provided);
	application_collection.spary_weight=1.7f;
	System.out.println("Spary weight is:"+application_collection.spary_weight);
	application_collection.spary_height=8.0;
	System.out.println("Spary height is:"+application_collection.spary_height);
	application_collection.spary_volume=200;
	System.out.println("Spary volume is:"+application_collection.spary_volume);
	application_collection.spary1_name="Posion";
	System.out.println("Spary name is:"+application_collection.spary1_name);
	application_collection.spary1_price=220;
	System.out.println("Spary price is:"+application_collection.spary1_price);
	application_collection.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+application_collection.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");
		Spary information=new Spary();
		information.spary_name="Fog";
	System.out.println("Spary name is:"+information.spary_name);
	information.spary_price=200;
	System.out.println("Spary price is:"+information.spary_price);
	information.spary_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+information.spary_manufacture_per_Year);
	information.spary_manufacture_Year=2019;
	System.out.println("Spary rating is:"+information.spary_manufacture_Year);
	information.spary_rating=5;
	System.out.println("Spary rating is:"+information.spary_rating);
	information.spary_is_good=true;
	System.out.println("Spary Usage is good :"+information.spary_is_good);
	information.spary_grade_provided='A';
	System.out.println("Spary Grade is:"+information.spary_grade_provided);
	information.spary_weight=1.7f;
	System.out.println("Spary weight is:"+information.spary_weight);
	information.spary_height=8.0;
	System.out.println("Spary height is:"+information.spary_height);
	information.spary_volume=200;
	System.out.println("Spary volume is:"+information.spary_volume);
	information.spary1_name="Posion";
	System.out.println("Spary name is:"+information.spary1_name);
	information.spary1_price=220;
	System.out.println("Spary price is:"+information.spary1_price);
	information.spary1_manufacture_per_Year=100000L;
	System.out.println("Spary man/year is:"+information.spary1_manufacture_per_Year);
	System.out.println("--------------End--------------");

	
	}




}





