public class TableRunner{
	public static void main(String args[]){
	Table.company_name1="Fortune";
	System.out.println("Table company is:"+Table.company_name1);
	Table.table_price1=2000;
	System.out.println("Table price is:"+Table.table_price1);
	Table.table_manufacture_per_Year1=1500L;
	System.out.println("Table man/year is:"+Table.table_manufacture_per_Year1);
	Table.table_manufacture_Year1=2020;
	System.out.println("Table manufacture in is:"+Table.table_manufacture_Year1);
	Table.table_rating1=5;
	System.out.println("Table rating is:"+Table.table_rating1);
	Table.table_is_suitable_for_kitchen1=true;
	System.out.println("Table is good:"+Table.table_is_suitable_for_kitchen1);
	Table.table_ranking_provided1='A';
	System.out.println("Table ranking is:"+Table.table_ranking_provided1);
	Table.table_weight1=150.0f;
	System.out.println("Table weight is:"+Table.table_weight1);
	Table.table_height1=49.9;
	System.out.println("Table height is:"+Table.table_height1);
	Table.table_quality1="Teak Wood";
	System.out.println("Table quality is:"+Table.table_quality1);
	Table.table1_name1="My Furniture Town";
	System.out.println("Table company is:"+Table.table1_name1);
	Table.table1_price1=20000L;
	System.out.println("Table price is:"+Table.table1_price1);
	Table.table1_total_trees_use1=5;
	System.out.println("Tree use is:"+Table.table1_total_trees_use1);
	System.out.println("--------------static End--------------");

	
	 Table product=new  Table();
	product.company_name="Fortune";
	System.out.println("Company name is:"+product.company_name);
	product.table_price=2000;
	System.out.println("Table price is:"+product.table_price);
	product.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+product.table_manufacture_per_Year);
	product.table_manufacture_Year=2020;
	System.out.println("Table man in :"+product.table_manufacture_Year);
	product.table_rating=5;
	System.out.println("Table rating is:"+product.table_rating);
	product.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+product.table_is_suitable_for_kitchen);
	product.table_ranking_provided='A';
	System.out.println("Table Grade is:"+product.table_ranking_provided);
	product.table_weight=150.0f;
	System.out.println("Table weight is:"+product.table_weight);
	product.table_height=49.9;
	System.out.println("Table height is:"+product.table_height);
	product.table_quality="Teak Wood";
	System.out.println("Table quality is:"+product.table_quality);
	product.table1_name="My Furniture Town";
	System.out.println("Table company is:"+product.table1_name);
	product.table1_price=25000;
	System.out.println("Table price is:"+product.table1_price);
	product.table1_total_trees_use=5;
	System.out.println("Trees use is:"+product.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table detail=new  Table();
	detail.company_name="Fortune";
	System.out.println("Company name is:"+detail.company_name);
	detail.table_price=2000;
	System.out.println("Table price is:"+detail.table_price);
	detail.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+detail.table_manufacture_per_Year);
	detail.table_manufacture_Year=2020;
	System.out.println("Table man in :"+detail.table_manufacture_Year);
	detail.table_rating=5;
	System.out.println("Table rating is:"+detail.table_rating);
	detail.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+detail.table_is_suitable_for_kitchen);
	detail.table_ranking_provided='A';
	System.out.println("Table Grade is:"+detail.table_ranking_provided);
	detail.table_weight=150.0f;
	System.out.println("Table weight is:"+detail.table_weight);
	detail.table_height=49.9;
	System.out.println("Table height is:"+detail.table_height);
	detail.table_quality="Teak Wood";
	System.out.println("Table quality is:"+detail.table_quality);
	detail.table1_name="My Furniture Town";
	System.out.println("Table company is:"+detail.table1_name);
	detail.table1_price=25000;
	System.out.println("Table price is:"+detail.table1_price);
	detail.table1_total_trees_use=5;
	System.out.println("Trees use is:"+detail.table1_total_trees_use);
	System.out.println("--------------End--------------");
	 Table amazon=new  Table();
	amazon.company_name="Fortune";
	System.out.println("Company name is:"+amazon.company_name);
	amazon.table_price=2000;
	System.out.println("Table price is:"+amazon.table_price);
	amazon.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+amazon.table_manufacture_per_Year);
	amazon.table_manufacture_Year=2020;
	System.out.println("Table man in :"+amazon.table_manufacture_Year);
	amazon.table_rating=5;
	System.out.println("Table rating is:"+amazon.table_rating);
	amazon.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+amazon.table_is_suitable_for_kitchen);
	amazon.table_ranking_provided='A';
	System.out.println("Table Grade is:"+amazon.table_ranking_provided);
	amazon.table_weight=150.0f;
	System.out.println("Table weight is:"+amazon.table_weight);
	amazon.table_height=49.9;
	System.out.println("Table height is:"+amazon.table_height);
	amazon.table_quality="Teak Wood";
	System.out.println("Table quality is:"+amazon.table_quality);
	amazon.table1_name="My Furniture Town";
	System.out.println("Table company is:"+amazon.table1_name);
	amazon.table1_price=25000;
	System.out.println("Table price is:"+amazon.table1_price);
	amazon.table1_total_trees_use=5;
	System.out.println("Trees use is:"+amazon.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table flipkart=new  Table();
		flipkart.company_name="Fortune";
	System.out.println("Company name is:"+flipkart.company_name);
	flipkart.table_price=2000;
	System.out.println("Table price is:"+flipkart.table_price);
	flipkart.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+flipkart.table_manufacture_per_Year);
	flipkart.table_manufacture_Year=2020;
	System.out.println("Table man in :"+flipkart.table_manufacture_Year);
	flipkart.table_rating=5;
	System.out.println("Table rating is:"+flipkart.table_rating);
	flipkart.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+flipkart.table_is_suitable_for_kitchen);
	flipkart.table_ranking_provided='A';
	System.out.println("Table Grade is:"+flipkart.table_ranking_provided);
	flipkart.table_weight=150.0f;
	System.out.println("Table weight is:"+flipkart.table_weight);
	flipkart.table_height=49.9;
	System.out.println("Table height is:"+flipkart.table_height);
	flipkart.table_quality="Teak Wood";
	System.out.println("Table quality is:"+flipkart.table_quality);
	flipkart.table1_name="My Furniture Town";
	System.out.println("Table company is:"+flipkart.table1_name);
	flipkart.table1_price=25000;
	System.out.println("Table price is:"+flipkart.table1_price);
	flipkart.table1_total_trees_use=5;
	System.out.println("Trees use is:"+flipkart.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table info=new  Table();
		info.company_name="Fortune";
	System.out.println("Company name is:"+info.company_name);
	info.table_price=2000;
	System.out.println("Table price is:"+info.table_price);
	info.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+info.table_manufacture_per_Year);
	info.table_manufacture_Year=2020;
	System.out.println("Table man in :"+info.table_manufacture_Year);
	info.table_rating=5;
	System.out.println("Table rating is:"+info.table_rating);
	info.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+info.table_is_suitable_for_kitchen);
	info.table_ranking_provided='A';
	System.out.println("Table Grade is:"+info.table_ranking_provided);
	info.table_weight=150.0f;
	System.out.println("Table weight is:"+info.table_weight);
	info.table_height=49.9;
	System.out.println("Table height is:"+info.table_height);
	info.table_quality="Teak Wood";
	System.out.println("Table quality is:"+info.table_quality);
	info.table1_name="My Furniture Town";
	System.out.println("Table company is:"+info.table1_name);
	info.table1_price=25000;
	System.out.println("Table price is:"+info.table1_price);
	info.table1_total_trees_use=5;
	System.out.println("Trees use is:"+info.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table table=new  Table();
		table.company_name="Fortune";
	System.out.println("Company name is:"+table.company_name);
	table.table_price=2000;
	System.out.println("Table price is:"+table.table_price);
	table.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+table.table_manufacture_per_Year);
	table.table_manufacture_Year=2020;
	System.out.println("Table man in :"+table.table_manufacture_Year);
	table.table_rating=5;
	System.out.println("Table rating is:"+table.table_rating);
	table.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+table.table_is_suitable_for_kitchen);
	table.table_ranking_provided='A';
	System.out.println("Table Grade is:"+table.table_ranking_provided);
	table.table_weight=150.0f;
	System.out.println("Table weight is:"+table.table_weight);
	table.table_height=49.9;
	System.out.println("Table height is:"+table.table_height);
	table.table_quality="Teak Wood";
	System.out.println("Table quality is:"+table.table_quality);
	table.table1_name="My Furniture Town";
	System.out.println("Table company is:"+table.table1_name);
	table.table1_price=25000;
	System.out.println("Table price is:"+table.table1_price);
	table.table1_total_trees_use=5;
	System.out.println("Trees use is:"+table.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table requirements=new  Table();
		requirements.company_name="Fortune";
	System.out.println("Company name is:"+requirements.company_name);
	requirements.table_price=2000;
	System.out.println("Table price is:"+requirements.table_price);
	requirements.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+requirements.table_manufacture_per_Year);
	requirements.table_manufacture_Year=2020;
	System.out.println("Table man in :"+requirements.table_manufacture_Year);
	requirements.table_rating=5;
	System.out.println("Table rating is:"+requirements.table_rating);
	requirements.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+requirements.table_is_suitable_for_kitchen);
	requirements.table_ranking_provided='A';
	System.out.println("Table Grade is:"+requirements.table_ranking_provided);
	requirements.table_weight=150.0f;
	System.out.println("Table weight is:"+requirements.table_weight);
	requirements.table_height=49.9;
	System.out.println("Table height is:"+requirements.table_height);
	requirements.table_quality="Teak Wood";
	System.out.println("Table quality is:"+requirements.table_quality);
	requirements.table1_name="My Furniture Town";
	System.out.println("Table company is:"+requirements.table1_name);
	requirements.table1_price=25000;
	System.out.println("Table price is:"+requirements.table1_price);
	requirements.table1_total_trees_use=5;
	System.out.println("Trees use is:"+requirements.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table features=new  Table();
		features.company_name="Fortune";
	System.out.println("Company name is:"+features.company_name);
	features.table_price=2000;
	System.out.println("Table price is:"+features.table_price);
	features.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+features.table_manufacture_per_Year);
	features.table_manufacture_Year=2020;
	System.out.println("Table man in :"+features.table_manufacture_Year);
	features.table_rating=5;
	System.out.println("Table rating is:"+features.table_rating);
	features.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+features.table_is_suitable_for_kitchen);
	features.table_ranking_provided='A';
	System.out.println("Table Grade is:"+features.table_ranking_provided);
	features.table_weight=150.0f;
	System.out.println("Table weight is:"+features.table_weight);
	features.table_height=49.9;
	System.out.println("Table height is:"+features.table_height);
	features.table_quality="Teak Wood";
	System.out.println("Table quality is:"+features.table_quality);
	features.table1_name="My Furniture Town";
	System.out.println("Table company is:"+features.table1_name);
	features.table1_price=25000;
	System.out.println("Table price is:"+features.table1_price);
	features.table1_total_trees_use=5;
	System.out.println("Trees use is:"+features.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table table_info=new  Table();
		table_info.company_name="Fortune";
	System.out.println("Company name is:"+table_info.company_name);
	table_info.table_price=2000;
	System.out.println("Table price is:"+table_info.table_price);
	table_info.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+table_info.table_manufacture_per_Year);
	table_info.table_manufacture_Year=2020;
	System.out.println("Table man in :"+table_info.table_manufacture_Year);
	table_info.table_rating=5;
	System.out.println("Table rating is:"+table_info.table_rating);
	table_info.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+table_info.table_is_suitable_for_kitchen);
	table_info.table_ranking_provided='A';
	System.out.println("Table Grade is:"+table_info.table_ranking_provided);
	table_info.table_weight=150.0f;
	System.out.println("Table weight is:"+table_info.table_weight);
	table_info.table_height=49.9;
	System.out.println("Table height is:"+table_info.table_height);
	table_info.table_quality="Teak Wood";
	System.out.println("Table quality is:"+table_info.table_quality);
	table_info.table1_name="My Furniture Town";
	System.out.println("Table company is:"+table_info.table1_name);
	table_info.table1_price=25000;
	System.out.println("Table price is:"+table_info.table1_price);
	table_info.table1_total_trees_use=5;
	System.out.println("Trees use is:"+table_info.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table table_detail=new  Table();
	table_detail.company_name="Fortune";
	System.out.println("Company name is:"+table_detail.company_name);
	table_detail.table_price=2000;
	System.out.println("Table price is:"+table_detail.table_price);
	table_detail.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+table_detail.table_manufacture_per_Year);
	table_detail.table_manufacture_Year=2020;
	System.out.println("Table man in :"+table_detail.table_manufacture_Year);
	table_detail.table_rating=5;
	System.out.println("Table rating is:"+table_detail.table_rating);
	table_detail.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+table_detail.table_is_suitable_for_kitchen);
	table_detail.table_ranking_provided='A';
	System.out.println("Table Grade is:"+table_detail.table_ranking_provided);
	table_detail.table_weight=150.0f;
	System.out.println("Table weight is:"+table_detail.table_weight);
	table_detail.table_height=49.9;
	System.out.println("Table height is:"+table_detail.table_height);
	table_detail.table_quality="Teak Wood";
	System.out.println("Table quality is:"+table_detail.table_quality);
	table_detail.table1_name="My Furniture Town";
	System.out.println("Table company is:"+table_detail.table1_name);
	table_detail.table1_price=25000;
	System.out.println("Table price is:"+table_detail.table1_price);
	table_detail.table1_total_trees_use=5;
	System.out.println("Trees use is:"+table_detail.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table buyers=new  Table();
	buyers.company_name="Fortune";
	System.out.println("Company name is:"+buyers.company_name);
	buyers.table_price=2000;
	System.out.println("Table price is:"+buyers.table_price);
	buyers.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+buyers.table_manufacture_per_Year);
	buyers.table_manufacture_Year=2020;
	System.out.println("Table man in :"+buyers.table_manufacture_Year);
	buyers.table_rating=5;
	System.out.println("Table rating is:"+buyers.table_rating);
	buyers.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+buyers.table_is_suitable_for_kitchen);
	buyers.table_ranking_provided='A';
	System.out.println("Table Grade is:"+buyers.table_ranking_provided);
	buyers.table_weight=150.0f;
	System.out.println("Table weight is:"+buyers.table_weight);
	buyers.table_height=49.9;
	System.out.println("Table height is:"+buyers.table_height);
	buyers.table_quality="Teak Wood";
	System.out.println("Table quality is:"+buyers.table_quality);
	buyers.table1_name="My Furniture Town";
	System.out.println("Table company is:"+buyers.table1_name);
	buyers.table1_price=25000;
	System.out.println("Table price is:"+buyers.table1_price);
	buyers.table1_total_trees_use=5;
	System.out.println("Trees use is:"+buyers.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table table_information=new  Table();
	table_information.company_name="Fortune";
	System.out.println("Company name is:"+table_information.company_name);
	table_information.table_price=2000;
	System.out.println("Table price is:"+table_information.table_price);
	table_information.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+table_information.table_manufacture_per_Year);
	table_information.table_manufacture_Year=2020;
	System.out.println("Table man in :"+table_information.table_manufacture_Year);
	table_information.table_rating=5;
	System.out.println("Table rating is:"+table_information.table_rating);
	table_information.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+table_information.table_is_suitable_for_kitchen);
	table_information.table_ranking_provided='A';
	System.out.println("Table Grade is:"+table_information.table_ranking_provided);
	table_information.table_weight=150.0f;
	System.out.println("Table weight is:"+table_information.table_weight);
	table_information.table_height=49.9;
	System.out.println("Table height is:"+table_information.table_height);
	table_information.table_quality="Teak Wood";
	System.out.println("Table quality is:"+table_information.table_quality);
	table_information.table1_name="My Furniture Town";
	System.out.println("Table company is:"+table_information.table1_name);
	table_information.table1_price=25000;
	System.out.println("Table price is:"+table_information.table1_price);
	table_information.table1_total_trees_use=5;
	System.out.println("Trees use is:"+table_information.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table viewers=new  Table();
	viewers.company_name="Fortune";
	System.out.println("Company name is:"+viewers.company_name);
	viewers.table_price=2000;
	System.out.println("Table price is:"+viewers.table_price);
	viewers.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+viewers.table_manufacture_per_Year);
	viewers.table_manufacture_Year=2020;
	System.out.println("Table man in :"+viewers.table_manufacture_Year);
	viewers.table_rating=5;
	System.out.println("Table rating is:"+viewers.table_rating);
	viewers.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+viewers.table_is_suitable_for_kitchen);
	viewers.table_ranking_provided='A';
	System.out.println("Table Grade is:"+viewers.table_ranking_provided);
	viewers.table_weight=150.0f;
	System.out.println("Table weight is:"+viewers.table_weight);
	viewers.table_height=49.9;
	System.out.println("Table height is:"+viewers.table_height);
	viewers.table_quality="Teak Wood";
	System.out.println("Table quality is:"+viewers.table_quality);
	viewers.table1_name="My Furniture Town";
	System.out.println("Table company is:"+viewers.table1_name);
	viewers.table1_price=25000;
	System.out.println("Table price is:"+viewers.table1_price);
	viewers.table1_total_trees_use=5;
	System.out.println("Trees use is:"+viewers.table1_total_trees_use);
	System.out.println("--------------End--------------");
	 Table furnitures=new  Table();
	furnitures.company_name="Fortune";
	System.out.println("Company name is:"+furnitures.company_name);
	furnitures.table_price=2000;
	System.out.println("Table price is:"+furnitures.table_price);
	furnitures.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+furnitures.table_manufacture_per_Year);
	furnitures.table_manufacture_Year=2020;
	System.out.println("Table man in :"+furnitures.table_manufacture_Year);
	furnitures.table_rating=5;
	System.out.println("Table rating is:"+furnitures.table_rating);
	furnitures.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+furnitures.table_is_suitable_for_kitchen);
	furnitures.table_ranking_provided='A';
	System.out.println("Table Grade is:"+furnitures.table_ranking_provided);
	furnitures.table_weight=150.0f;
	System.out.println("Table weight is:"+furnitures.table_weight);
	furnitures.table_height=49.9;
	System.out.println("Table height is:"+furnitures.table_height);
	furnitures.table_quality="Teak Wood";
	System.out.println("Table quality is:"+furnitures.table_quality);
	furnitures.table1_name="My Furniture Town";
	System.out.println("Table company is:"+furnitures.table1_name);
	furnitures.table1_price=25000;
	System.out.println("Table price is:"+furnitures.table1_price);
	furnitures.table1_total_trees_use=5;
	System.out.println("Trees use is:"+furnitures.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table furniture_collection=new  Table();
	furniture_collection.company_name="Fortune";
	System.out.println("Company name is:"+furniture_collection.company_name);
	furniture_collection.table_price=2000;
	System.out.println("Table price is:"+furniture_collection.table_price);
	furniture_collection.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+furniture_collection.table_manufacture_per_Year);
	furniture_collection.table_manufacture_Year=2020;
	System.out.println("Table man in :"+furniture_collection.table_manufacture_Year);
	furniture_collection.table_rating=5;
	System.out.println("Table rating is:"+furniture_collection.table_rating);
	furniture_collection.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+furniture_collection.table_is_suitable_for_kitchen);
	furniture_collection.table_ranking_provided='A';
	System.out.println("Table Grade is:"+furniture_collection.table_ranking_provided);
	furniture_collection.table_weight=150.0f;
	System.out.println("Table weight is:"+furniture_collection.table_weight);
	furniture_collection.table_height=49.9;
	System.out.println("Table height is:"+furniture_collection.table_height);
	furniture_collection.table_quality="Teak Wood";
	System.out.println("Table quality is:"+furniture_collection.table_quality);
	furniture_collection.table1_name="My Furniture Town";
	System.out.println("Table company is:"+furniture_collection.table1_name);
	furniture_collection.table1_price=25000;
	System.out.println("Table price is:"+furniture_collection.table1_price);
	furniture_collection.table1_total_trees_use=5;
	System.out.println("Trees use is:"+furniture_collection.table1_total_trees_use);
	System.out.println("--------------End--------------");
		 Table application_collection=new  Table();
	application_collection.company_name="Fortune";
	System.out.println("Company name is:"+application_collection.company_name);
	application_collection.table_price=2000;
	System.out.println("Table price is:"+application_collection.table_price);
	application_collection.table_manufacture_per_Year=1500L;
	System.out.println("Table man/year by is:"+application_collection.table_manufacture_per_Year);
	application_collection.table_manufacture_Year=2020;
	System.out.println("Table man in :"+application_collection.table_manufacture_Year);
	application_collection.table_rating=5;
	System.out.println("Table rating is:"+application_collection.table_rating);
	application_collection.table_is_suitable_for_kitchen=true;
	System.out.println("Table Usage is good :"+application_collection.table_is_suitable_for_kitchen);
	application_collection.table_ranking_provided='A';
	System.out.println("Table Grade is:"+application_collection.table_ranking_provided);
	application_collection.table_weight=150.0f;
	System.out.println("Table weight is:"+application_collection.table_weight);
	application_collection.table_height=49.9;
	System.out.println("Table height is:"+application_collection.table_height);
	application_collection.table_quality="Teak Wood";
	System.out.println("Table quality is:"+application_collection.table_quality);
	application_collection.table1_name="My Furniture Town";
	System.out.println("Table company is:"+application_collection.table1_name);
	application_collection.table1_price=25000;
	System.out.println("Table price is:"+application_collection.table1_price);
	application_collection.table1_total_trees_use=5;
	System.out.println("Trees use is:"+application_collection.table1_total_trees_use);
	System.out.println("--------------End--------------");

	
	}




}





