public class AnimalRunner{
	public static void main(String args[]){
	Animal animal=new Animal();
	System.out.println("Animal name is:"+animal.animal_name);
	System.out.println("MaleLion price is:"+animal.lifespan);
	System.out.println("MaleLion man/year is:"+animal.total_population);
	System.out.println("MaleLion man in year is:"+animal.weight);
	System.out.println("MaleLion rating is:"+animal.colour);
	System.out.println("MaleLion is suitable is:"+animal.height);
	System.out.println("MaleLion rank is:"+animal.population_decreasing);
	System.out.println("MaleLion weight is:"+animal.animal_ability_test_grade);
	System.out.println("MaleLion types is:"+animal.teeth);
	System.out.println("MaleLion millage is:"+animal.muscle_energy);
	System.out.println("Animal name is:"+animal.animal1_name);
	System.out.println("FemaleLion  price is:"+animal.colour);
	System.out.println("FemaleLion capacity is:"+animal.lifespan1);
	System.out.println("FemaleLion man in year is:"+animal.weight1);
	System.out.println("FemaleLion rating is:"+animal.height1);
	System.out.println("FemaleLion weight is:"+animal.animal_ability_test1_grade);
	System.out.println("FemaleLion milliage used is:"+animal.muscle_energy1);
		Animal animal_detail=new Animal();
	System.out.println("Animal name is:"+animal_detail.animal_name);
	System.out.println("MaleLion price is:"+animal_detail.lifespan);
	System.out.println("MaleLion man/year is:"+animal_detail.total_population);
	System.out.println("MaleLion man in year is:"+animal_detail.weight);
	System.out.println("MaleLion rating is:"+animal_detail.colour);
	System.out.println("MaleLion is suitable is:"+animal_detail.height);
	System.out.println("MaleLion rank is:"+animal_detail.population_decreasing);
	System.out.println("MaleLion weight is:"+animal_detail.animal_ability_test_grade);
	System.out.println("MaleLion types is:"+animal_detail.teeth);
	System.out.println("MaleLion millage is:"+animal_detail.muscle_energy);
	System.out.println("Animal name is:"+animal_detail.animal1_name);
	System.out.println("FemaleLion  price is:"+animal_detail.colour);
	System.out.println("FemaleLion capacity is:"+animal_detail.lifespan1);
	System.out.println("FemaleLion man in year is:"+animal_detail.weight1);
	System.out.println("FemaleLion rating is:"+animal_detail.height1);
	System.out.println("FemaleLion weight is:"+animal_detail.animal_ability_test1_grade);
	System.out.println("FemaleLion milliage used is:"+animal_detail.muscle_energy1);
		Animal animal_info=new Animal();
	System.out.println("Animal name is:"+animal_info.animal_name);
	System.out.println("MaleLion price is:"+animal_info.lifespan);
	System.out.println("MaleLion man/year is:"+animal_info.total_population);
	System.out.println("MaleLion man in year is:"+animal_info.weight);
	System.out.println("MaleLion rating is:"+animal_info.colour);
	System.out.println("MaleLion is suitable is:"+animal_info.height);
	System.out.println("MaleLion rank is:"+animal_info.population_decreasing);
	System.out.println("MaleLion weight is:"+animal_info.animal_ability_test_grade);
	System.out.println("MaleLion types is:"+animal_info.teeth);
	System.out.println("MaleLion millage is:"+animal_info.muscle_energy);
	System.out.println("Animal name is:"+animal_info.animal1_name);
	System.out.println("FemaleLion  price is:"+animal_info.colour);
	System.out.println("FemaleLion capacity is:"+animal_info.lifespan1);
	System.out.println("FemaleLion man in year is:"+animal_info.weight1);
	System.out.println("FemaleLion rating is:"+animal_info.height1);
	System.out.println("FemaleLion weight is:"+animal_info.animal_ability_test1_grade);
	System.out.println("FemaleLion milliage used is:"+animal_info.muscle_energy1);
		Animal animal_collection=new Animal();
	System.out.println("Animal name is:"+animal_collection.animal_name);
	System.out.println("MaleLion price is:"+animal_collection.lifespan);
	System.out.println("MaleLion man/year is:"+animal_collection.total_population);
	System.out.println("MaleLion man in year is:"+animal_collection.weight);
	System.out.println("MaleLion rating is:"+animal_collection.colour);
	System.out.println("MaleLion is suitable is:"+animal_collection.height);
	System.out.println("MaleLion rank is:"+animal_collection.population_decreasing);
	System.out.println("MaleLion weight is:"+animal_collection.animal_ability_test_grade);
	System.out.println("MaleLion types is:"+animal_collection.teeth);
	System.out.println("MaleLion millage is:"+animal_collection.muscle_energy);
	System.out.println("Animal name is:"+animal_collection.animal1_name);
	System.out.println("FemaleLion  price is:"+animal_collection.colour);
	System.out.println("FemaleLion capacity is:"+animal_collection.lifespan1);
	System.out.println("FemaleLion man in year is:"+animal_collection.weight1);
	System.out.println("FemaleLion rating is:"+animal_collection.height1);
	System.out.println("FemaleLion weight is:"+animal_collection.animal_ability_test1_grade);
	System.out.println("FemaleLion milliage used is:"+animal_collection.muscle_energy1);
	}
}